### ISSUE TITLE
ERROR: SiftGPU not fully supported

### ISSUE THREAD

**Issue by visonpon** [colmap/colmap#1019]
Hi, I got an error when I use colmap on google colab:

ERROR: SiftGPU not fully supported.
ERROR: SiftGPU not fully supported.
ERROR: SiftGPU not fully supported.
ERROR: SiftGPU not fully supported.
    @     0x7fb38cc9ef33  google::LogMessage::SendToLog()
    @     0x7fb3882e38a0 (unknown)
    @     0x7fb38cc9cc28  google::LogMessage::Flush()
    @     0x7fb386fa4f47 gsignal
    @     0x7fb38cc9f999  google::LogMessageFatal::~LogMessageFatal()
    @     0x55cb9767400d  (unknown)
    @     0x55cb97674043  (unknown)
    @     0x7fb386fa68b1 abort
    @     0x7fb387bf96df  (unknown)
    @     0x7fb387bc8957 (unknown)
    @     0x7fb3882d86db  start_thread
    @     0x7fb387bceae6 (unknown)
    @     0x7fb387087a3f  clone
Traceback (most recent call last):
  File "imgs2poses.py", line 18, in <module>
    gen_poses(args.scenedir, args.match_type)
  File "/content/LLFF/llff/poses/pose_utils.py", line 268, in gen_poses
    run_colmap(basedir, match_type)
  File "/content/LLFF/llff/poses/colmap_wrapper.py", line 37, in run_colmap
    feat_output = ( subprocess.check_output(feature_extractor_args, universal_newlines=True) )
  File "/usr/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['colmap', 'feature_extractor', '--database_path', '/content/drive/My Drive/nerf/flower/database.db', '--image_path', '/content/drive/My Drive/nerf/flower/images', '--ImageReader.single_camera', '1']' died with <Signals.SIGABRT: 6>.

And when I set` '--SiftExtraction.use_gpu', '0' , I got anther error 

CheckCudaDevice:	no CUDA-capable device is detected
Features matched
Sparse map created
Finished running COLMAP, see /content/drive/My Drive/nerf/flower/colmap_output.txt for logs
Post-colmap
Traceback (most recent call last):
  File "imgs2poses.py", line 18, in <module>
    gen_poses(args.scenedir, args.match_type)
  File "/content/LLFF/llff/poses/pose_utils.py", line 274, in gen_poses
    poses, pts3d, perm = load_colmap_data(basedir)
  File "/content/LLFF/llff/poses/pose_utils.py", line 14, in load_colmap_data
    camdata = read_model.read_cameras_binary(camerasfile)
  File "/content/LLFF/llff/poses/colmap_read_model.py", line 115, in read_cameras_binary
    with open(path_to_model_file, "rb") as fid:
FileNotFoundError: [Errno 2] No such file or directory: '/content/drive/My Drive/nerf/flower/sparse/0/cameras.bin'

**Comment by rlangefe** [comment]
I also ran into this. I was hoping to run this section on a system that doesn't have a GPU. Have you found a solution?

**Comment by Shadowphax** [comment]
You need to reinstall your GPU driver. Also, recompile GPU support for Colmap.

**Comment by rlangefe** [comment]
I think we found that when you compile it with GPU support, it refused to run without a GPU. Our drivers were correctly installed, but it would only run completely on the GPU node. So yeah, run it with a GPU available or it can't run this part of the reconstruction process.

**Comment by yasminebhs123** [comment]
hi , i have the same issue any sollution please!!
