### ISSUE TITLE
Qt errors causing a segfault on colmap gui

### ISSUE THREAD

**Issue by KBentley57** [colmap/colmap#1221]
After building Colmap (from git, as of yesterday) and some of its dependencies from source, I get an error somewhere in Qt while trying to run the gui.  I haven't used it much yet, but other functionality seems to be working fine.  The exact error is shown in the box below, as well as the backtrace from gdb.  I'm running CentOS 7, CUDA 11.3, with 2x GTX 1080's, and everything is up to date.  Any advice on what to do to troubleshoot this issue?  I've seen other posts about similar problems with Qt.

**Error**
*** Aborted at 1620831439 (unix time) try "date -d @1620831439" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGSEGV (@0xd8) received by PID 20618 (TID 0x7f200ebc8000) from PID 216; stack trace: ***
    @     0x7f202c61b756 google::(anonymous namespace)::FailureSignalHandler()
    @     0x7f202995a630 (unknown)
    @           0x7f6648 colmap::ModelViewerWidget::initializeGL()
    @     0x7f202ab5e02a (unknown)
    @     0x7f202ab5e1ca QOpenGLWidget::resizeEvent()
    @     0x7f202ab3fff1 QWidget::event()
    @     0x7f202ab01d8c QApplicationPrivate::notify_helper()
    @     0x7f202ab08f68 QApplication::notify()
    @     0x7f202a292b36 QCoreApplication::notifyInternal2()
    @     0x7f202ab38a92 QWidgetPrivate::sendPendingMoveAndResizeEvents()
    @     0x7f202ab3c5f3 QWidgetPrivate::show_helper()
    @     0x7f202ab3f407 QWidget::setVisible()
    @     0x7f202ab3c580 QWidgetPrivate::showChildren()
    @     0x7f202ab3c60f QWidgetPrivate::show_helper()
    @     0x7f202ab3f407 QWidget::setVisible()
    @           0x58d0c6 colmap::RunGraphicalUserInterface()
    @           0x56d36d main
    @     0x7f202874d555 __libc_start_main
    @           0x576d47 (unknown)
    @                0x0 (unknown)
Segmentation fault (core dumped)

**Bactrace**
Thread 1 "colmap" received signal SIGSEGV, Segmentation fault.
**0x00000000007f6648 in QOpenGLFunctions_3_2_Core::glEnable (this=0x5746030, cap=2929) at /usr/include/qt5/QtGui/qopenglfunctions_3_2_core.h:502
502	    d_1_0_Core->f.Enable(cap);**
(gdb) bt
#0  0x00000000007f6648 in QOpenGLFunctions_3_2_Core::glEnable(unsigned int) (this=0x5746030, cap=2929) at /usr/include/qt5/QtGui/qopenglfunctions_3_2_core.h:502
#1  0x00000000007f6648 in colmap::ModelViewerWidget::initializeGL() (this=0x5746000) at /home/bentleykw/src/SupportPackages/build/colmap/src/colmap/src/ui/model_viewer_widget.cc:218
#2  0x00007ffff63ca02a in QOpenGLWidgetPrivate::initialize() () at /lib64/libQt5Widgets.so.5
#3  0x00007ffff63ca1ca in QOpenGLWidget::resizeEvent(QResizeEvent*) () at /lib64/libQt5Widgets.so.5
#4  0x00007ffff63abff1 in QWidget::event(QEvent*) () at /lib64/libQt5Widgets.so.5
#5  0x00007ffff636dd8c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /lib64/libQt5Widgets.so.5
#6  0x00007ffff6374f68 in QApplication::notify(QObject*, QEvent*) () at /lib64/libQt5Widgets.so.5
#7  0x00007ffff5afeb36 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /lib64/libQt5Core.so.5
#8  0x00007ffff63a4a92 in QWidgetPrivate::sendPendingMoveAndResizeEvents(bool, bool) () at /lib64/libQt5Widgets.so.5
#9  0x00007ffff63a85f3 in QWidgetPrivate::show_helper() () at /lib64/libQt5Widgets.so.5
#10 0x00007ffff63ab407 in QWidget::setVisible(bool) () at /lib64/libQt5Widgets.so.5
#11 0x00007ffff63a8580 in QWidgetPrivate::showChildren(bool) () at /lib64/libQt5Widgets.so.5
#12 0x00007ffff63a860f in QWidgetPrivate::show_helper() () at /lib64/libQt5Widgets.so.5
#13 0x00007ffff63ab407 in QWidget::setVisible(bool) () at /lib64/libQt5Widgets.so.5
#14 0x000000000058d0c6 in colmap::RunGraphicalUserInterface(int, char**) (argc=<optimized out>, argv=0x7fffffffd9d0)
    at /home/bentleykw/src/SupportPackages/build/colmap/src/colmap/src/exe/gui.cc:66
#15 0x000000000056d36d in std::function<int (int, char**)>::operator()(int, char**) const (__args#1=<optimized out>, __args#0=<optimized out>, this=0x7fffffffd890)
    at /opt/rh/devtoolset-9/root/usr/include/c++/9/bits/std_function.h:683
#16 0x000000000056d36d in main(int, char**) (argc=2, argv=0x7fffffffd9c8) at /home/bentleykw/src/SupportPackages/build/colmap/src/colmap/src/exe/colmap.cc:173

**glxinfo -B**
bentleykw@centos:~/src/SupportPackages$ glxinfo -B
name of display: :0
display: :0  screen: 0
direct rendering: No (If you want to find out why, try setting LIBGL_DEBUG=verbose)
Memory info (GL_NVX_gpu_memory_info):
    Dedicated video memory: 0 MB
    Total available memory: 0 MB
    Currently available dedicated video memory: 0 MB
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: GeForce GTX 1080/PCIe/SSE2
OpenGL version string: 3.0.0 NVIDIA 440.64
Warning: GL error 0x500 at line 560
OpenGL shading language version string: 1.30 NVIDIA via Cg compiler
OpenGL context flags: (none)
Warning: GL error 0x500 at line 576

OpenGL ES profile version string: 3.0.0 NVIDIA 440.64
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 1.00

**Linux Kernel**
3.10.0-1160.15.2.el7.x86_64

**qtdiag**

Qt 5.9.7 (x86_64-little_endian-lp64 shared (dynamic) release build; by GCC 4.8.5 20150623 (Red Hat 4.8.5-44)) on "xcb" 
OS: CentOS Linux 7 (Core) [linux version 3.10.0-1160.15.2.el7.x86_64]

Architecture: x86_64; features: SSE2 SSE3 SSSE3 SSE4.1 SSE4.2 AVX AVX2 RTM HLE

Environment:
  QTDIR="/usr/lib64/qt-3.3"
  QTINC="/usr/lib64/qt-3.3/include"
  QTLIB="/usr/lib64/qt-3.3/lib"
  QT_GRAPHICSSYSTEM_CHECKED="1"
  QT_IM_MODULE="ibus"
  QT_PLUGIN_PATH="/usr/lib64/kde4/plugins:/usr/lib/kde4/plugins"

Features: QT_NO_EXCEPTIONS

Library info:
  PrefixPath: /usr/lib64/qt5
  DocumentationPath: /usr/share/doc/qt5
  HeadersPath: /usr/include/qt5
  LibrariesPath: /usr/lib64
  LibraryExecutablesPath: /usr/lib64/qt5/libexec
  BinariesPath: /usr/lib64/qt5/bin
  PluginsPath: /usr/lib64/qt5/plugins
  ImportsPath: /usr/lib64/qt5/imports
  Qml2ImportsPath: /usr/lib64/qt5/qml
  ArchDataPath: /usr/lib64/qt5
  DataPath: /usr/share/qt5
  TranslationsPath: /usr/share/qt5/translations
  ExamplesPath: /usr/lib64/qt5/examples
  TestsPath: /usr/lib64/qt5/tests
  SettingsPath: /etc/xdg

Network:
  Using "OpenSSL 1.0.2k-fips  26 Jan 2017", version: 0x100020bf

Platform capabilities: ThreadedPixmaps OpenGL ThreadedOpenGL WindowMasks MultipleWindows ForeignWindows NonFullScreenWindows NativeWidgets WindowManagement SyncState RasterGLSurface SwitchableWidgetComposition

Style hints:
  mouseDoubleClickInterval: 400
  mousePressAndHoldInterval: 500
  startDragDistance: 8
  startDragTime: 500
  startDragVelocity: 0
  keyboardInputInterval: 400
  keyboardAutoRepeatRate: 30
  cursorFlashTime: 1200
  showIsFullScreen: 0
  showIsMaximized: 0
  passwordMaskDelay: 0
  passwordMaskCharacter: U+2022
  fontSmoothingGamma: 1.7
  useRtlExtensions: 0
  setFocusOnTouchRelease: 0
  tabFocusBehavior: Qt::TabFocusBehavior(TabFocusAllControls) 
  singleClickActivation: 0

Additional style hints (QPlatformIntegration):
  ReplayMousePressOutsidePopup: 0

Theme:
  Platforms requested : gtk3,gnome,generic
            available : gtk3
  Styles requested    : fusion,windows
         available    : Windows,Fusion
  Icon theme          : Adwaita,  from /usr/share/icons,/usr/share/pixmaps
  System font         : "Cantarell" 11
  Native file dialog
  Native color dialog
  Native font dialog

Fonts:
  General font : "Cantarell" 11
  Fixed font   : "monospace" 11
  Title font   : "DejaVu Sans" 12
  Smallest font: "DejaVu Sans" 12

Palette:
  WindowText: #ff000000
  Button: #ffefebe7
  Light: #ffffffff
  Midlight: #ffcbc7c4
  Dark: #ff9f9d9a
  Mid: #ffb8b5b2
  Text: #ff000000
  BrightText: #ffffffff
  ButtonText: #ff000000
  Base: #ffffffff
  Window: #ffefebe7
  Shadow: #ff767472
  Highlight: #ff308cc6
  HighlightedText: #ffffffff
  Link: #ff0000ff
  LinkVisited: #ffff00ff
  AlternateBase: #fff7f5f3
  NoRole: #ff000000
  ToolTipBase: #ffffffdc
  ToolTipText: #ff000000

Screens: 2, High DPI scaling: inactive
# 0 "DVI-D-0" Depth: 24 Primary: yes
  Manufacturer: 
  Model: 
  Serial number: 
  Geometry: 1920x1080+1920+0 Available: 1920x1014+1920+28
  Virtual geometry: 3840x1080+0+0 Available: 3840x1014+0+28
  2 virtual siblings
  Physical size: 598x336 mm  Refresh: 60 Hz Power state: 0
  Physical DPI: 81.5518,81.6429 Logical DPI: 96,96 Subpixel_None
  DevicePixelRatio: 1 Pixel density: 1
  Primary orientation: 2 Orientation: 2 Native orientation: 0 OrientationUpdateMask: 0

# 1 "DP-2" Depth: 24 Primary: no
  Manufacturer: 
  Model: 
  Serial number: 
  Geometry: 1920x1080+0+0 Available: 1920x1014+0+28
  Virtual geometry: 3840x1080+0+0 Available: 3840x1014+0+28
  2 virtual siblings
  Physical size: 598x336 mm  Refresh: 60 Hz Power state: 0
  Physical DPI: 81.5518,81.6429 Logical DPI: 96,96 Subpixel_None
  DevicePixelRatio: 1 Pixel density: 1
  Primary orientation: 2 Orientation: 2 Native orientation: 0 OrientationUpdateMask: 0

LibGL Vendor: NVIDIA Corporation
Renderer: GeForce GTX 1080/PCIe/SSE2
Version: 3.0.0 NVIDIA 440.64
Shading language: 1.30 NVIDIA via Cg compiler
Format: Version: 3.0 Profile: 0 Swap behavior: 0 Buffer size (RGB): 8,8,8 Depth buffer: 24

**Comment by KBentley57** [comment]
All,

As soon as I posted the bug I realized that my OpenGL was a bit out of date. I updated my NVidia drivers to 465 and that seemed to fix the issue.  glxinfo now reports below.  Consider this issue closed.

**glxinfo -B**
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Memory info (GL_NVX_gpu_memory_info):
    Dedicated video memory: 8192 MB
    Total available memory: 8192 MB
    Currently available dedicated video memory: 7892 MB
OpenGL vendor string: NVIDIA Corporation
OpenGL renderer string: NVIDIA GeForce GTX 1080/PCIe/SSE2
OpenGL core profile version string: 4.6.0 NVIDIA 465.19.01
OpenGL core profile shading language version string: 4.60 NVIDIA
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 4.6.0 NVIDIA 465.19.01
OpenGL shading language version string: 4.60 NVIDIA
OpenGL context flags: (none)
OpenGL profile mask: (none)

OpenGL ES profile version string: OpenGL ES 3.2 NVIDIA 465.19.01
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
