### ISSUE TITLE
running python img2poses.py ERROR

### ISSUE THREAD

**Issue by asbeg** [colmap/colmap#1305]
Hello 
i am trying to run `python img2poses.py $your-images-folder`  to get camera poses for training (Neural Radiance Fields) and get this ERROR. 
Can you explain what the problem might be and how to fix it

``` 
Need to run COLMAP
[option_manager.cc:811] Check failed: ExistsDir(*image_path)
ERROR: Invalid options provided.
Traceback (most recent call last):
  File "imgs2poses.py", line 18, in <module>
    gen_poses(args.scenedir, args.match_type)
  File "/Users/ab/ProjectTest/LLFF/llff/poses/pose_utils.py", line 268, in gen_poses
    run_colmap(basedir, match_type)
  File "/Users/ab/ProjectTest/LLFF/llff/poses/colmap_wrapper.py", line 35, in run_colmap
    feat_output = ( subprocess.check_output(feature_extractor_args, universal_newlines=True) )
  File "/opt/anaconda3/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/opt/anaconda3/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['colmap', 
'feature_extractor', '--database_path', '/Users/ab/ProjectTest/imgs_nerf/database.db', 
'--image_path', '/Users/ab/ProjectTest/imgs_nerf/images', 
'--ImageReader.single_camera', '1']' returned non-zero exit status 1.
```

**Comment by tsattler** [comment]
The parameter `'--image_path', '/Users/ab/ProjectTest/imgs_nerf/images'` means that Colmap expects that the images are stored in the folder `/Users/ab/ProjectTest/imgs_nerf/images'`. The error message `[option_manager.cc:811] Check failed: ExistsDir(*image_path)` seems to indicate that this directory does not exist.

**Comment by yatin9136** [comment]
Need to run COLMAP
[option_manager.cc:795] Check failed: ExistsDir(*image_path)
ERROR: Invalid options provided.
Traceback (most recent call last):
  File "imgs2poses.py", line 18, in <module>
    gen_poses(args.scenedir, args.match_type)
  File "/home/yaten/ceres-solver/build/colmap/build/LLFF/llff/poses/pose_utils.py", line 268, in gen_poses
    run_colmap(basedir, match_type)
  File "/home/yaten/ceres-solver/build/colmap/build/LLFF/llff/poses/colmap_wrapper.py", line 35, in run_colmap
    feat_output = ( subprocess.check_output(feature_extractor_args, universal_newlines=True) )
  File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['colmap', 'feature_extractor', '--database_path', '/home/yaten/data/database.db', '--image_path', '/home/yaten/data/images', '--ImageReader.single_camera', '1']' returned non-zero exit status 1.

**Comment by yatin9136** [comment]
can you tell me how to solve this problem

Need to run COLMAP
[option_manager.cc:795] Check failed: ExistsDir(*image_path)
ERROR: Invalid options provided.
Traceback (most recent call last):
  File "imgs2poses.py", line 18, in <module>
    gen_poses(args.scenedir, args.match_type)
  File "/home/yaten/ceres-solver/build/colmap/build/LLFF/llff/poses/pose_utils.py", line 268, in gen_poses
    run_colmap(basedir, match_type)
  File "/home/yaten/ceres-solver/build/colmap/build/LLFF/llff/poses/colmap_wrapper.py", line 35, in run_colmap
    feat_output = ( subprocess.check_output(feature_extractor_args, universal_newlines=True) )
  File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['colmap', 'feature_extractor', '--database_path', '/home/yaten/data/database.db', '--image_path', '/home/yaten/data/images', '--ImageReader.single_camera', '1']' returned non-zero exit status 1.

**Comment by tsattler** [comment]
The error says that the directory specified by the `--image_path` parameter does not exist.

**Comment by yatin9136** [comment]
please help in it after that getting this


Need to run COLMAP
qt.qpa.xcb: could not connect to display
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.

*** Aborted at 1672216455 (unix time) try "date -d @1672216455" if you are using GNU date ***
PC: @     0x7f0e97cbb00b gsignal
*** SIGABRT (@0x530a) received by PID 21258 (TID 0x7f0e93f51940) from PID 21258; stack trace: ***
    @     0x7f0e99d13631 (unknown)
    @     0x7f0e99cea420 (unknown)
    @     0x7f0e97cbb00b gsignal
    @     0x7f0e97c9a859 abort
    @     0x7f0e98303aad QMessageLogger::fatal()
    @     0x7f0e988e57ae QGuiApplicationPrivate::createPlatformIntegration()
    @     0x7f0e988e6708 QGuiApplicationPrivate::createEventDispatcher()
    @     0x7f0e9850af55 QCoreApplicationPrivate::init()
    @     0x7f0e988e8543 QGuiApplicationPrivate::init()
    @     0x7f0e98f253bd QApplicationPrivate::init()
    @     0x5596acb28ae3 colmap::RunFeatureExtractor()
    @     0x5596acb18a42 main
    @     0x7f0e97c9c083 __libc_start_main
    @     0x5596acb1cd0e _start
Traceback (most recent call last):
  File "imgs2poses.py", line 18, in <module>
    gen_poses(args.scenedir, args.match_type)
  File "/home/yaten/test/ceres-solver/build/colmap/build/LLFF/llff/poses/pose_utils.py", line 268, in gen_poses
    run_colmap(basedir, match_type)
  File "/home/yaten/test/ceres-solver/build/colmap/build/LLFF/llff/poses/colmap_wrapper.py", line 35, in run_colmap
    feat_output = ( subprocess.check_output(feature_extractor_args, universal_newlines=True) )
  File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['colmap', 'feature_extractor', '--database_path', '/home/yaten/test/ceres-solver/build/colmap/build/database.db', '--image_path', '/home/yaten/test/ceres-solver/build/colmap/build/images', '--ImageReader.single_camera', '1']' died with <Signals.SIGABRT: 6>.

**Comment by tsattler** [comment]
As the error message said, Colmap can't connect to a display. In particular, it cannot connect to a display through the Qt plugin. How did you install Colmap?

**Comment by yatin9136** [comment]
i used gcp vm instance and gone with each and every step but still not working

**Comment by Williamarvin** [comment]
please help Need to run COLMAP
Traceback (most recent call last):
  File "imgs2poses.py", line 18, in <module>
    gen_poses(args.scenedir, args.match_type)
  File "C:\Users\willi\OneDrive\Desktop\instantngp2\LLFF\llff\poses\pose_utils.py", line 268, in gen_poses
    run_colmap(basedir, match_type)
  File "C:\Users\willi\OneDrive\Desktop\instantngp2\LLFF\llff\poses\colmap_wrapper.py", line 35, in run_colmap
    feat_output = ( subprocess.check_output(feature_extractor_args, universal_newlines=True) )
  File "C:\Users\willi\anaconda3\anaconda\envs\dnerf\lib\subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "C:\Users\willi\anaconda3\anaconda\envs\dnerf\lib\subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\willi\anaconda3\anaconda\envs\dnerf\lib\subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "C:\Users\willi\anaconda3\anaconda\envs\dnerf\lib\subprocess.py", line 1017, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by nocnestudio** [comment]
on windows conda is using location\location   ;   on linux conda is using location/location ; difference is "\" to "/"
