### ISSUE TITLE
running python img2poses.py ERROR

### ISSUE THREAD

**Issue by 1309123499** [colmap/colmap#1367]
Hello
i am trying to run python img2poses.py $your-images-folder to get camera poses for training (Neural Radiance Fields) and get this ERROR.
Can you explain what the problem might be and how to fix it

Need to run COLMAP
Features extracted
Features matched
ERROR: failed to create sparse model
Traceback (most recent call last):
  File "imgs2poses.py", line 18, in <module>
    gen_poses(args.scenedir, args.match_type)
  File "/data/NeRF_xy/llff/poses/pose_utils.py", line 268, in gen_poses
    run_colmap(basedir, match_type)
  File "/data/NeRF_xy/llff/poses/colmap_wrapper.py", line 71, in run_colmap
    map_output = ( subprocess.check_output(mapper_args, universal_newlines=True) )
  File "/opt/conda/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/opt/conda/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/usr/local/bin/colmap', 'mapper', '--database_path', 'data/f2/database.db', '--image_path', 'data/f2/images', '--output_path', 'data/f2/sparse', '--Mapper.num_threads', '16', '--Mapper.init_min_tri_angle', '4', '--Mapper.multiple_models', '0', '--Mapper.extract_colors', '0']' returned non-zero exit status 1.

btw, i got the output.txt
==============================================================================
Feature extraction
==============================================================================

Processed file [1/1]
  Name:            IMG_4027.JPG
  Dimensions:      3998 x 2998
  Camera:          #1 - SIMPLE_RADIAL
  Focal Length:    4797.60px
  Features:        11995
Elapsed time: 0.007 [minutes]

==============================================================================
Exhaustive feature matching
==============================================================================

Matching block [1/1, 1/1] in 0.000s
Elapsed time: 0.003 [minutes]
 i also got  a database.db which is not empty(1837K),but got error in the next step

**Comment by tsattler** [comment]
It seems that your database only contains a single image. A single image is not sufficient to run structure-from-motion.

**Comment by hust-kevin** [comment]
@tsattler I have 15 images,  also get this error

**Comment by tsattler** [comment]
@hust-kevin Can you show the output of Colmap?

**Comment by hust-kevin** [comment]
```shell
Need to run COLMAP
Features extracted
Features matched
ERROR: failed to create sparse model
Traceback (most recent call last):
  File "imgs2poses.py", line 18, in <module>
    gen_poses(args.scenedir, args.match_type)
  File "/content/LLFF/llff/poses/pose_utils.py", line 268, in gen_poses
    run_colmap(basedir, match_type)
  File "/content/LLFF/llff/poses/colmap_wrapper.py", line 71, in run_colmap
    map_output = ( subprocess.check_output(mapper_args, universal_newlines=True) )
  File "/usr/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['colmap', 'mapper', '--database_path', '/content/drive/MyDrive/nerf/database.db', '--image_path', '/content/drive/MyDrive/nerf/images', '--output_path', '/content/drive/MyDrive/nerf/sparse', '--Mapper.num_threads', '16', '--Mapper.init_min_tri_angle', '4', '--Mapper.multiple_models', '0', '--Mapper.extract_colors', '0']' returned non-zero exit status 1.
```

colmap.txt
```sh
==============================================================================
Feature extraction
==============================================================================

Processed file [1/15]
  Name:            resize_1.jpg
  Dimensions:      512 x 512
  Camera:          #1 - SIMPLE_RADIAL
  Focal Length:    614.40px
  Features:        45
Processed file [2/15]
  Name:            resize_10.jpg
  Dimensions:      512 x 512
  Camera:          #1 - SIMPLE_RADIAL
  Focal Length:    614.40px
  Features:        51
Processed file [3/15]
  Name:            resize_11.jpg
  Dimensions:      512 x 512
  Camera:          #1 - SIMPLE_RADIAL
  Focal Length:    614.40px
  Features:        74
Processed file [4/15]
  Name:            resize_12.jpg
  Dimensions:      512 x 512
  Camera:          #1 - SIMPLE_RADIAL
  Focal Length:    614.40px
  Features:        61
Processed file [5/15]
  Name:            resize_13.jpg
  Dimensions:      512 x 512
  Camera:          #1 - SIMPLE_RADIAL
  Focal Length:    614.40px
  Features:        34
Processed file [6/15]
  Name:            resize_14.jpg
  Dimensions:      512 x 512
  Camera:          #1 - SIMPLE_RADIAL
  Focal Length:    614.40px
  Features:        73
Processed file [7/15]
  Name:            resize_15.jpg
  Dimensions:      512 x 512
  Camera:          #1 - SIMPLE_RADIAL
  Focal Length:    614.40px
  Features:        70
Processed file [8/15]
  Name:            resize_16.jpg
  Dimensions:      512 x 512
  Camera:          #1 - SIMPLE_RADIAL
  Focal Length:    614.40px
  Features:        63
Processed file [9/15]
  Name:            resize_2.jpg
  Dimensions:      512 x 512
  Camera:          #1 - SIMPLE_RADIAL
  Focal Length:    614.40px
  Features:        53
Processed file [10/15]
  Name:            resize_3.jpg
  Dimensions:      512 x 512
  Camera:          #1 - SIMPLE_RADIAL
  Focal Length:    614.40px
  Features:        109
Processed file [11/15]
  Name:            resize_4.jpg
  Dimensions:      512 x 512
  Camera:          #1 - SIMPLE_RADIAL
  Focal Length:    614.40px
  Features:        63
Processed file [12/15]
  Name:            resize_5.jpg
  Dimensions:      512 x 512
  Camera:          #1 - SIMPLE_RADIAL
  Focal Length:    614.40px
  Features:        115
Processed file [13/15]
  Name:            resize_6.jpg
  Dimensions:      512 x 512
  Camera:          #1 - SIMPLE_RADIAL
  Focal Length:    614.40px
  Features:        118
Processed file [14/15]
  Name:            resize_7.jpg
  Dimensions:      512 x 512
  Camera:          #1 - SIMPLE_RADIAL
  Focal Length:    614.40px
  Features:        58
Processed file [15/15]
  Name:            resize_8.jpg
  Dimensions:      512 x 512
  Camera:          #1 - SIMPLE_RADIAL
  Focal Length:    614.40px
  Features:        83
Elapsed time: 0.123 [minutes]

==============================================================================
Exhaustive feature matching
==============================================================================

Matching block [1/1, 1/1] in 0.018s
Elapsed time: 0.003 [minutes]
```

**Comment by tsattler** [comment]
Can you also show the output of the sparse reconstruction stage?

Looking at the feature extraction process, it seems that very few features are found per image. I assume that Colmap has a hard time finding enough correct matches to initialize the 3D reconstruction (per default, I think 100 correct matches are required) and to add the other images to the initial two-view model (I think 30 correct matches are required). You could adjust the corresponding parameters to see whether this helps. If you have control over the image resolution, I would suggest running Colmap on higher resolution images first as this should lead to more features.

**Comment by hyeok-jong** [comment]
Hi 

I also had a similar [problem](https://github.com/colmap/colmap/issues/1446)

For several tests I found that, for me, the error was due to version(cimmit) of ceres-solver.

And I fixed the version and full code is [here](https://colab.research.google.com/drive/1FoZ9RmxpE-ltIASCmpHg0WdETPoDmtex?usp=sharing)

**Comment by mfzsl** [comment]
I also had the problem, can you share me the full code.
Thank you.

**Comment by hyeok-jong** [comment]
@mfzsl See [here](https://github.com/hyeok-jong/Install_COLMAP)
