### ISSUE TITLE
Mismatch between number of images and number of poses! Please rerun COLMAP!

### ISSUE THREAD

**Issue by Hzurang** [colmap/colmap#1497]
Hello, I wanted to ask why does this issue arise?

I'm trying to run train.py file.Then these errors appear.

/content/nerf_pl
INFO:numexpr.utils:NumExpr defaulting to 2 threads.
INFO:lightning:GPU available: True, used: True
INFO:lightning:CUDA_VISIBLE_DEVICES: [0]
Traceback (most recent call last):
  File "train.py", line 180, in <module>
    trainer.fit(system)
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/trainer/trainer.py", line 730, in fit
    model.prepare_data()
  File "train.py", line 80, in prepare_data
    self.train_dataset = dataset(split='train', **kwargs)
  File "/content/nerf_pl/datasets/llff.py", line 173, in __init__
    self.read_meta()
  File "/content/nerf_pl/datasets/llff.py", line 183, in read_meta
    'Mismatch between number of images and number of poses! Please rerun COLMAP!'
AssertionError: Mismatch between number of images and number of poses! Please rerun COLMAP!

How should I solve it?

**Comment by tsattler** [comment]
This seems to be the same question as in #1487 .

The error is not caused by Colmap but by the code from the repository that you are using. I would recommend asking there for help.
