### ISSUE TITLE
undefined symbol: TIFFFieldDataType, version LIBTIFF_4.0 on Ubuntu20.04

### ISSUE THREAD

**Issue by WHU-Dewran** [colmap/colmap#1937]
I have all the packages installed on Ubuntu 20.04.
But everytime I run the code related to colmap, occurs the error:
`ImportError: /lib/x86_64-linux-gnu/libfreeimage.so.3: undefined symbol: TIFFFieldDataType, version LIBTIFF_4.0`
Has anyone experienced the same problem in ubuntu 20.04？
Seeking for help...

**Comment by WHU-Dewran** [comment]
> Same problem here, have you found a solution? @WHU-Dewran

Yeah! `conda uninstall libtiff` works for me.
I hope it will also works for you!

**Comment by jiangyijin** [comment]
Hello, I am also setting up the limap environment. After uninstalling libtiff using conda, I encountered the following issue: When I run python -c "import limap", I received a ModuleNotFoundError: No module named 'PIL.Image'.
I am using CUDA 11.8 and torch 1.3.1. Here are the specific issues:
(pytorch) ubuntu@ml-ubuntu20-04-desktop-v1-0-108gb-100m:~/Desktop/limap$ python -c "import limap"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ubuntu/Desktop/limap/limap/__init__.py", line 6, in <module>
    from . import point2d
  File "/home/ubuntu/Desktop/limap/limap/point2d/__init__.py", line 1, in <module>
    from .superpoint import *
  File "/home/ubuntu/Desktop/limap/limap/point2d/superpoint/__init__.py", line 1, in <module>
    from .main import run_superpoint
  File "/home/ubuntu/Desktop/limap/limap/point2d/superpoint/main.py", line 12, in <module>
    from hloc import extract_features
  File "/home/ubuntu/Desktop/limap/third-party/Hierarchical-Localization/hloc/extract_features.py", line 12, in <module>
    import PIL.Image
ModuleNotFoundError: No module named 'PIL.Image'
Before I used conda uninstall libtiff, I also encountered the issue of Undefined symbol: TIFFFieldDataType, version LIBTIFF_4.0 on Ubuntu 20.04.

**Comment by jiangyijin** [comment]
Hello, I am also setting up the limap environment. After uninstalling libtiff using conda, I encountered the following issue: When I run python -c "import limap", I received a ModuleNotFoundError: No module named 'PIL.Image'.
I am using CUDA 11.8 and torch 1.3.1. Here are the specific issues:
(pytorch) ubuntu@ml-ubuntu20-04-desktop-v1-0-108gb-100m:~/Desktop/limap$ python -c "import limap"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ubuntu/Desktop/limap/limap/__init__.py", line 6, in <module>
    from . import point2d
  File "/home/ubuntu/Desktop/limap/limap/point2d/__init__.py", line 1, in <module>
    from .superpoint import *
  File "/home/ubuntu/Desktop/limap/limap/point2d/superpoint/__init__.py", line 1, in <module>
    from .main import run_superpoint
  File "/home/ubuntu/Desktop/limap/limap/point2d/superpoint/main.py", line 12, in <module>
    from hloc import extract_features
  File "/home/ubuntu/Desktop/limap/third-party/Hierarchical-Localization/hloc/extract_features.py", line 12, in <module>
    import PIL.Image
ModuleNotFoundError: No module named 'PIL.Image'
Before I used conda uninstall libtiff, I also encountered the issue of Undefined symbol: TIFFFieldDataType, version LIBTIFF_4.0 on Ubuntu 20.04.

**Comment by jiangyijin** [comment]
> Hello, I am also setting up the limap environment. After uninstalling libtiff using conda, I encountered the following issue: When I run python -c "import limap", I received a ModuleNotFoundError: No module named 'PIL.Image'. I am using CUDA 11.8 and torch 1.3.1. Here are the specific issues: (pytorch) ubuntu@ml-ubuntu20-04-desktop-v1-0-108gb-100m:~/Desktop/limap$ python -c "import limap" Traceback (most recent call last): File "", line 1, in File "/home/ubuntu/Desktop/limap/limap/**init**.py", line 6, in from . import point2d File "/home/ubuntu/Desktop/limap/limap/point2d/**init**.py", line 1, in from .superpoint import * File "/home/ubuntu/Desktop/limap/limap/point2d/superpoint/**init**.py", line 1, in from .main import run_superpoint File "/home/ubuntu/Desktop/limap/limap/point2d/superpoint/main.py", line 12, in from hloc import extract_features File "/home/ubuntu/Desktop/limap/third-party/Hierarchical-Localization/hloc/extract_features.py", line 12, in import PIL.Image ModuleNotFoundError: No module named 'PIL.Image' Before I used conda uninstall libtiff, I also encountered the issue of Undefined symbol: TIFFFieldDataType, version LIBTIFF_4.0 on Ubuntu 20.04.

colmap3.8, torch1.13.1 and cuda18

**Comment by ahojnnes** [comment]
Closing: libtiff symbol conflict caused by conda environment; resolved by uninstalling conda libtiff.
