### ISSUE TITLE
Trying to run imgs2poses.py but got this error

### ISSUE THREAD

**Issue by Williamarvin** [colmap/colmap#1960]
Need to run COLMAP
Traceback (most recent call last):
  File "imgs2poses.py", line 18, in <module>
    gen_poses(args.scenedir, args.match_type)
  File "C:\Users\willi\OneDrive\Desktop\instantngp2\LLFF\llff\poses\pose_utils.py", line 268, in gen_poses
    run_colmap(basedir, match_type)
  File "C:\Users\willi\OneDrive\Desktop\instantngp2\LLFF\llff\poses\colmap_wrapper.py", line 35, in run_colmap
    feat_output = ( subprocess.check_output(feature_extractor_args, universal_newlines=True) )
  File "C:\Users\willi\anaconda3\anaconda\envs\dnerf\lib\subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "C:\Users\willi\anaconda3\anaconda\envs\dnerf\lib\subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\willi\anaconda3\anaconda\envs\dnerf\lib\subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "C:\Users\willi\anaconda3\anaconda\envs\dnerf\lib\subprocess.py", line 1017, in _execute_child
/FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by tsattler** [comment]
Does Colmap produce an error message (it cannot find a file, etc.)? Or can the system not find Colmap?

**Comment by ahojnnes** [comment]
Closing: not a COLMAP bug; Python/LLFF environment FileNotFoundError.
