### ISSUE TITLE
Segfault in feature-extractor since copy constructor is avoided (Colmap >3.7, 18th of May)

### ISSUE THREAD

**Issue by jhgoebbert** [colmap/colmap#2120]
Hello everyone,

we are facing a reproducible segfault with any Colmap >3.7 in colmap::SiftFeatureExtractor when calling
```
 colmap feature_extractor --image_path ./south-building/images --database_path ./south-building/database.db
```

This issue was introduced in the commit from the 18th of May https://github.com/colmap/colmap/commit/5695733d1a582cd667526cb38404fdf3a486a76a named `Avoid the calling of copy constructor/assignment`.
The builds of commit-versions before the 18th of May succeed and build of commit-versions since this commit fail with a segfault reproducible. 

This was tested on GPU-nodes of the hpc system [JURECA](https://apps.fz-juelich.de/jsc/hps/jureca/configuration.html) with 128 cores and 4 GPUs and maybe more likely to occur here because of the high number of cores.

Please expand the following sections for more details:
<details>
  <summary>Console output</summary>
The segfault can appear directly with the first image but sometimes it takes a few images until it fails:

```
[goebbert1@jrlogin08 colmap]$ colmap feature_extractor --image_path ./south-building-images/south-building/images --database_path ./south-building-images/south-building/database.db

==============================================================================
Feature extraction
==============================================================================

Processed file [1/128]
  Name:            P1180141.JPG
  SKIP: Features for image already extracted.
Processed file [2/128]
  Name:            P1180142.JPG
  SKIP: Features for image already extracted.
Processed file [3/128]
  Name:            P1180143.JPG
  SKIP: Features for image already extracted.
Processed file [4/128]
  Name:            P1180145.JPG
  SKIP: Features for image already extracted.
Processed file [5/128]
  Name:            P1180144.JPG
  SKIP: Features for image already extracted.
Processed file [6/128]
  Name:            P1180146.JPG
  SKIP: Features for image already extracted.
Processed file [7/128]
  Name:            P1180147.JPG
  SKIP: Features for image already extracted.
Processed file [8/128]
  Name:            P1180148.JPG
  SKIP: Features for image already extracted.
Processed file [9/128]
  Name:            P1180149.JPG
  SKIP: Features for image already extracted.
Processed file [10/128]
  Name:            P1180150.JPG
  SKIP: Features for image already extracted.
Processed file [11/128]
  Name:            P1180151.JPG
  SKIP: Features for image already extracted.
Processed file [12/128]
  Name:            P1180152.JPG
  SKIP: Features for image already extracted.
Processed file [13/128]
  Name:            P1180153.JPG
  SKIP: Features for image already extracted.
*** Aborted at 1692427898 (unix time) try "date -d @1692427898" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGSEGV (@0x0) received by PID 6439 (TID 0x7fb8e3fff000) from PID 0; stack trace: ***
    @     0x7fb94002c306 google::(anonymous namespace)::FailureSignalHandler()
    @     0x7fb93da3acf0 (unknown)
    @           0x6f5d6c colmap::internal::ImageData::ImageData()
    @           0x6f7945 std::deque<>::_M_push_back_aux<>()
    @           0x6f7c8c colmap::JobQueue<>::Push()
    @           0x6f3c0c colmap::SiftFeatureExtractor::Run()
    @           0x814313 colmap::Thread::RunFunc()
    @     0x7fb93d4e3a44 execute_native_thread_routine
    @     0x7fb93da301ca start_thread
    @     0x7fb93cc96e73 __GI___clone
Segmentation fault (core dumped)
```
</details>

<details>
  <summary>Full Backtrace</summary>

The full backtrace the core-file using gdb reads:
```
#0  0x00000000006f5d6c in std::_Vector_base<colmap::FeatureKeypoint, std::allocator<colmap::FeatureKeypoint> >::_Vector_impl_data::_Vector_impl_data (
    __x=<error reading variable: dwarf2_find_location_expression: Corrupted DWARF expression.>, this=<error reading variable: dwarf2_find_location_expression: Corrupted DWARF expression.>)
    at /dev/shm/goebbert1/jurecadc/Colmap/3.7/gcccoremkl-11.3.0-2022.1.0-test/colmap-5695733d1a582cd667526cb38404fdf3a486a76a/src/feature/unique_ptr.h:104
No locals.
#1  std::_Vector_base<colmap::FeatureKeypoint, std::allocator<colmap::FeatureKeypoint> >::_Vector_impl::_Vector_impl (
    __x=<error reading variable: dwarf2_find_location_expression: Corrupted DWARF expression.>, this=<error reading variable: dwarf2_find_location_expression: Corrupted DWARF expression.>)
    at /p/software/jurecadc/stages/2023/software/GCCcore/11.3.0/include/c++/11.3.0/ext/image_reader.h:144
No locals.
#2  std::_Vector_base<colmap::FeatureKeypoint, std::allocator<colmap::FeatureKeypoint> >::_Vector_base (this=<error reading variable: dwarf2_find_location_expression: Corrupted DWARF expression.>)
    at /p/software/jurecadc/stages/2023/software/GCCcore/11.3.0/include/c++/11.3.0/ext/image_reader.h:308
No locals.
#3  std::vector<colmap::FeatureKeypoint, std::allocator<colmap::FeatureKeypoint> >::vector (this=<error reading variable: dwarf2_find_location_expression: Corrupted DWARF expression.>)
    at /p/software/jurecadc/stages/2023/software/GCCcore/11.3.0/include/c++/11.3.0/ext/image_reader.h:572
No locals.
#4  colmap::internal::ImageData::ImageData (this=0x7fb8c8029150) at /p/software/jurecadc/stages/2023/software/GCCcore/11.3.0/include/c++/11.3.0/new_allocator.h:93
No locals.
#5  0x00000000006f7945 in __gnu_cxx::new_allocator<colmap::internal::ImageData>::construct<colmap::internal::ImageData, colmap::internal::ImageData> (
    __p=<error reading variable: dwarf2_find_location_expression: Corrupted DWARF expression.>, this=0x3182f50)
    at /dev/shm/goebbert1/jurecadc/Colmap/3.7/gcccoremkl-11.3.0-2022.1.0-test/colmap-5695733d1a582cd667526cb38404fdf3a486a76a/src/feature/allocator.h:160
No locals.
#6  std::allocator_traits<std::allocator<colmap::internal::ImageData> >::construct<colmap::internal::ImageData, colmap::internal::ImageData> (
    __p=<error reading variable: dwarf2_find_location_expression: Corrupted DWARF expression.>, __a=...)
    at /dev/shm/goebbert1/jurecadc/Colmap/3.7/gcccoremkl-11.3.0-2022.1.0-test/colmap-5695733d1a582cd667526cb38404fdf3a486a76a/src/feature/hashtable_policy.h:516
No locals.
#7  std::deque<colmap::internal::ImageData, std::allocator<colmap::internal::ImageData> >::_M_push_back_aux<colmap::internal::ImageData> (this=this@entry=0x3182f50)
    at /p/software/jurecadc/stages/2023/software/GCCcore/11.3.0/include/c++/11.3.0/x86_64-pc-linux-gnu/bits/DenseCoeffsBase.h:501
No locals.
#8  0x00000000006f7c8c in std::deque<colmap::internal::ImageData, std::allocator<colmap::internal::ImageData> >::emplace_back<colmap::internal::ImageData> (this=0x3182f50)
    at /p/software/jurecadc/stages/2023/software/GCCcore/11.3.0/include/c++/11.3.0/atomicity.h:779
No locals.
#9  std::deque<colmap::internal::ImageData, std::allocator<colmap::internal::ImageData> >::push_back (__x=..., this=0x3182f50)
    at /dev/shm/goebbert1/jurecadc/Colmap/3.7/gcccoremkl-11.3.0-2022.1.0-test/colmap-5695733d1a582cd667526cb38404fdf3a486a76a/src/feature/stl_queue.h:1511
No locals.
#10 std::queue<colmap::internal::ImageData, std::deque<colmap::internal::ImageData, std::allocator<colmap::internal::ImageData> > >::push (__x=..., this=0x3182f50)
    at /dev/shm/goebbert1/jurecadc/Colmap/3.7/gcccoremkl-11.3.0-2022.1.0-test/colmap-5695733d1a582cd667526cb38404fdf3a486a76a/src/feature/std_mutex.h:271
No locals.
#11 colmap::JobQueue<colmap::internal::ImageData>::Push (this=this@entry=0x3182f40, data=...) at /dev/shm/goebbert1/jurecadc/Colmap/3.7/gcccoremkl-11.3.0-2022.1.0-test/easybuild_obj/src/extraction.h:371
        lock = {_M_device = 0x3182fa0, _M_owns = true}
#12 0x00000000006f3c0c in colmap::SiftFeatureExtractor::Run (this=0x7fffd31148c0) at /p/software/jurecadc/stages/2023/software/Boost.Python/1.79.0-GCCcore-11.3.0/include/boost/system/detail/bitmap.h:421
        image_data = {status = colmap::ImageReader::Status::IMAGE_EXISTS, camera = {camera_id_ = 4294967295, model_id_ = -1, width_ = 0, height_ = 0,
            params_ = {<std::_Vector_base<double, std::allocator<double> >> = {
                _M_impl = {<std::allocator<double>> = {<__gnu_cxx::new_allocator<double>> = {<No data fields>}, <No data fields>}, <std::_Vector_base<double, std::allocator<double> >::_Vector_impl_data> = {
                    _M_start = 0x0, _M_finish = 0x0, _M_end_of_storage = 0x0}, <No data fields>}}, <No data fields>}, prior_focal_length_ = false}, image = {image_id_ = 7, name_ = {
              static npos = 18446744073709551615, _M_dataplus = {<std::allocator<char>> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x7fb8e3fcf438 ""},
              _M_string_length = 0, {_M_local_buf = '\000' <repeats 15 times>, _M_allocated_capacity = 0}}, camera_id_ = 1, registered_ = false, num_points3D_ = 0, num_observations_ = 0,
            num_correspondences_ = 0, num_visible_points3D_ = 0,
            qvec_ = {<Eigen::PlainObjectBase<Eigen::Matrix<double, 4, 1, 0, 4, 1> >> = {<Eigen::MatrixBase<Eigen::Matrix<double, 4, 1, 0, 4, 1> >> = {<Eigen::DenseBase<Eigen::Matrix<double, 4, 1, 0, 4, 1> >> = {<Eigen::DenseCoeffsBase<Eigen::Matrix<double, 4, 1, 0, 4, 1>, 3>> = {<Eigen::DenseCoeffsBase<Eigen::Matrix<double, 4, 1, 0, 4, 1>, 1>> = {<Eigen::DenseCoeffsBase<Eigen::Matrix<double, 4, 1, 0, 4, 1>, 0>> = {<Eigen::EigenBase<Eigen::Matrix<double, 4, 1, 0, 4, 1> >> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, m_storage = {m_data = {
                    array = {1, 0, 0, 0}}}}, <No data fields>},
            tvec_ = {<Eigen::PlainObjectBase<Eigen::Matrix<double, 3, 1, 0, 3, 1> >> = {<Eigen::MatrixBase<Eigen::Matrix<double, 3, 1, 0, 3, 1> >> = {<Eigen::DenseBase<Eigen::Matrix<double, 3, 1, 0, 3, 1> >> = {<Eigen::DenseCoeffsBase<Eigen::Matrix<double, 3, 1, 0, 3, 1>, 3>> = {<Eigen::DenseCoeffsBase<Eigen::Matrix<double, 3, 1, 0, 3, 1>, 1>> = {<Eigen::DenseCoeffsBase<Eigen::Matrix<double, 3, 1, 0, 3, 1>, 0>> = {<Eigen::EigenBase<Eigen::Matrix<double, 3, 1, 0, 3, 1> >> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, m_storage = {m_data = {
                    array = {0, 0, 0}}}}, <No data fields>},
--Type <RET> for more, q to quit, c to continue without paging--
 1> >> = {<Eigen::DenseCoeffsBase<Eigen::Matrix<double, 4, 1, 0, 4, 1>, 3>> = {<Eigen::DenseCoeffsBase<Eigen::Matrix<double, 4, 1, 0, 4, 1>, 1>> = {<Eigen::DenseCoeffsBase<Eigen::Matrix<double, 4, 1, 0, 4, 1>, 0>> = {<Eigen::EigenBase<Eigen::Matrix<double, 4, 1, 0, 4, 1> >> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, m_storage = {m_data = {array = {nan(0x8000000000000), nan(0x8000000000000), nan(0x8000000000000), nan(0x8000000000000)}}}}, <No data fields>},
            tvec_prior_ = {<Eigen::PlainObjectBase<Eigen::Matrix<double, 3, 1, 0, 3, 1> >> = {<Eigen::MatrixBase<Eigen::Matrix<double, 3, 1, 0, 3, 1> >> = {<Eigen::DenseBase<Eigen::Matrix<double, 3, 1, 0, 3, 1> >> = {<Eigen::DenseCoeffsBase<Eigen::Matrix<double, 3, 1, 0, 3, 1>, 3>> = {<Eigen::DenseCoeffsBase<Eigen::Matrix<double, 3, 1, 0, 3, 1>, 1>> = {<Eigen::DenseCoeffsBase<Eigen::Matrix<double, 3, 1, 0, 3, 1>, 0>> = {<Eigen::EigenBase<Eigen::Matrix<double, 3, 1, 0, 3, 1> >> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, m_storage = {m_data = {
                    array = {nan(0x8000000000000), nan(0x8000000000000), nan(0x8000000000000)}}}}, <No data fields>}, points2D_ = {<std::vector<colmap::Point2D, Eigen::aligned_allocator<colmap::Point2D> >> = {<std::_Vector_base<colmap::Point2D, Eigen::aligned_allocator<colmap::Point2D> >> = {_M_impl = {<Eigen::aligned_allocator<colmap::Point2D>> = {<std::allocator<colmap::Point2D>> = {<__gnu_cxx::new_allocator<colmap::Point2D>> = {<No data fields>}, <No data fields>}, <No data fields>}, <std::_Vector_base<colmap::Point2D, Eigen::aligned_allocator<colmap::Point2D> >::_Vector_impl_data> = {_M_start = 0x0,
                      _M_finish = 0x0, _M_end_of_storage = 0x0}, <No data fields>}}, <No data fields>}, <No data fields>}, num_correspondences_have_point3D_ = {<std::_Vector_base<unsigned int, std::allocator<unsigned int> >> = {_M_impl = {<std::allocator<unsigned int>> = {<__gnu_cxx::new_allocator<unsigned int>> = {<No data fields>}, <No data fields>}, <std::_Vector_base<unsigned int, std::allocator<unsigned int> >::_Vector_impl_data> = {_M_start = 0x0, _M_finish = 0x0, _M_end_of_storage = 0x0}, <No data fields>}}, <No data fields>}, point3D_visibility_pyramid_ = {width_ = 0, height_ = 0, score_ = 0,
              max_score_ = 0, pyramid_ = {<std::_Vector_base<Eigen::Matrix<int, -1, -1, 0, -1, -1>, std::allocator<Eigen::Matrix<int, -1, -1, 0, -1, -1> > >> = {_M_impl = {<std::allocator<Eigen::Matrix<int, -1, -1, 0, -1, -1> >> = {<__gnu_cxx::new_allocator<Eigen::Matrix<int, -1, -1, 0, -1, -1> >> = {<No data fields>}, <No data fields>}, <std::_Vector_base<Eigen::Matrix<int, -1, -1, 0, -1, -1>, std::allocator<Eigen::Matrix<int, -1, -1, 0, -1, -1> > >::_Vector_impl_data> = {_M_start = 0x0, _M_finish = 0x0, _M_end_of_storage = 0x0}, <No data fields>}}, <No data fields>}}}, bitmap = {data_ = {
              _M_t = {<std::__uniq_ptr_impl<FIBITMAP, void (*)(FIBITMAP*)>> = {_M_t = {<std::_Tuple_impl<0, FIBITMAP*, void (*)(FIBITMAP*)>> = {<std::_Tuple_impl<1, void (*)(FIBITMAP*)>> = {<std::_Head_base<1, void (*)(FIBITMAP*), false>> = {_M_head_impl = 0x7fb93f85f310 <FreeImage_Unload>}, <No data fields>}, <std::_Head_base<0, FIBITMAP*, false>> = {_M_head_impl = 0x0}, <No data fields>}, <No data fields>}}, <No data fields>}}, width_ = 0, height_ = 0, channels_ = 0}, mask = {data_ = {_M_t = {<std::__uniq_ptr_impl<FIBITMAP, void (*)(FIBITMAP*)>> = {
                  _M_t = {<std::_Tuple_impl<0, FIBITMAP*, void (*)(FIBITMAP*)>> = {<std::_Tuple_impl<1, void (*)(FIBITMAP*)>> = {<std::_Head_base<1, void (*)(FIBITMAP*), false>> = {_M_head_impl = 0x7fb93f85f310 <FreeImage_Unload>}, <No data fields>}, <std::_Head_base<0, FIBITMAP*, false>> = {_M_head_impl = 0x0}, <No data fields>}, <No data fields>}}, <No data fields>}}, width_ = 0, height_ = 0, channels_ = 0}, keypoints = {<std::_Vector_base<colmap::FeatureKeypoint, std::allocator<colmap::FeatureKeypoint> >> = {
              _M_impl = {<std::allocator<colmap::FeatureKeypoint>> = {<__gnu_cxx::new_allocator<colmap::FeatureKeypoint>> = {<No data fields>}, <No data fields>}, <std::_Vector_base<colmap::FeatureKeypoint, std::allocator<colmap::FeatureKeypoint> >::_Vector_impl_data> = {_M_start = 0x0, _M_finish = 0x0, _M_end_of_storage = 0x0}, <No data fields>}}, <No data fields>},
          descriptors = {<Eigen::PlainObjectBase<Eigen::Matrix<unsigned char, -1, -1, 1, -1, -1> >> = {<Eigen::MatrixBase<Eigen::Matrix<unsigned char, -1, -1, 1, -1, -1> >> = {<Eigen::DenseBase<Eigen::Matrix<unsigned char, -1, -1, 1, -1, -1> >> = {<Eigen::DenseCoeffsBase<Eigen::Matrix<unsigned char, -1, -1, 1, -1, -1>, 3>> = {<Eigen::DenseCoeffsBase<Eigen::Matrix<unsigned char, -1, -1, 1, -1, -1>, 1>> = {<Eigen::DenseCoeffsBase<Eigen::Matrix<unsigned char, -1, -1, 1, -1, -1>, 0>> = {<Eigen::EigenBase<Eigen::Matrix<unsigned char, -1, -1, 1, -1, -1> >> = {<No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, <No data fields>}, m_storage = {m_data = 0x0, m_rows = 0, m_cols = 0}}, <No data fields>}}
#13 0x0000000000814313 in colmap::Thread::RunFunc (this=0x7fffd31148c0) at /dev/shm/goebbert1/jurecadc/Colmap/3.7/gcccoremkl-11.3.0-2022.1.0-test/colmap-5695733d1a582cd667526cb38404fdf3a486a76a/src/util/std_function.h:177
No locals.
#14 0x00007fb93d4e3a44 in std::execute_native_thread_routine (__p=0x31f5970) at ../../../../../libstdc++-v3/src/c++11/shared_ptr_base.h:82
        __t = <optimized out>
#15 0x00007fb93da301ca in start_thread () from /usr/lib64/libpthread.so.0
No symbol table info available.
#16 0x00007fb93cc96e73 in clone () from /usr/lib64/libc.so.6
No symbol table info available.

```
</details>

<details>
  <summary>Build configuration</summary>

- GCC 11.3.0
- CUDA/11.7
- Eigen/3.4.0
- Boost/1.79.0
- gflags/2.2.2
- glog/0.6.0
- SuiteSparse/5.13.0
- CGAL/5.5.1
- ceres-solver/2.1.0
- FreeImage/3.18.0
- FLANN/1.9.2
- SQLite/3.38.3
- Qt5/5.15.5

CMake options:
- CUDA_ENABLED=ON
- CMAKE_CUDA_ARCHITECTURES=all-major

More details can be found [HERE](https://github.com/easybuilders/JSC/blob/2023/Golden_Repo/c/Colmap/Colmap-3.8-gcccoremkl-11.3.0-2022.1.0.eb)

</details>

**Comment by ahojnnes** [comment]
Thanks for the backtrace. Will try to have a look in the next days.

**Comment by jhgoebbert** [comment]
Hi, I just wanted to ask if there are any news on this.
Our workaround is at the moment to un-patch the commit https://github.com/colmap/colmap/commit/5695733d1a582cd667526cb38404fdf3a486a76a

**Comment by ahojnnes** [comment]
Is this still an issue?

**Comment by ahojnnes** [comment]
Thank you. Conveniently, we plan to release a new version in the next few days. Please do report back even if the feedback is positive. Thanks.
