### ISSUE TITLE
ValueError: could not convert string to float: '3.9.1'

### ISSUE THREAD

**Issue by liu-bohan** [colmap/colmap#2394]
Does anyone meet the same problem?
```
Traceback (most recent call last):
  File "/home/liubohan/anaconda3/envs/nerfstudio/bin/ns-process-data", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/liubohan/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/nerfstudio/scripts/process_data.py", line 522, in entrypoint
    tyro.cli(Commands).main()
  File "/home/liubohan/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/nerfstudio/process_data/images_to_nerfstudio_dataset.py", line 112, in main
    self._run_colmap()
  File "/home/liubohan/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/nerfstudio/process_data/colmap_converter_to_nerfstudio_dataset.py", line 204, in _run_colmap
    colmap_utils.run_colmap(
  File "/home/liubohan/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/nerfstudio/process_data/colmap_utils.py", line 116, in run_colmap
    colmap_version = get_colmap_version(colmap_cmd)
  File "/home/liubohan/anaconda3/envs/nerfstudio/lib/python3.8/site-packages/nerfstudio/process_data/colmap_utils.py", line 61, in get_colmap_version
    return float(version)
ValueError: could not convert string to float: '3.9.1'
```

**Comment by liu-bohan** [comment]
I deeply look into the file _colmap_utils.py_, and below is how the function `get_colmap_version( )` implemented:

```
def get_colmap_version(colmap_cmd: str, default_version=3.8) -> float:
    """Returns the version of COLMAP.
    This code assumes that colmap returns a version string of the form
    "COLMAP 3.8 ..." which may not be true for all versions of COLMAP.

    Args:
        default_version: Default version to return if COLMAP version can't be determined.
    Returns:
        The version of COLMAP.
    """
    output = run_command(f"{colmap_cmd} -h", verbose=False)
    assert output is not None
    for line in output.split("\n"):
        if line.startswith("COLMAP"):
            version = line.split(" ")[1]
            version = "".join([c for c in version if c.isdigit() or c == "."])
            return float(version)
    CONSOLE.print(f"[bold red]Could not find COLMAP version. Using default {default_version}")
    return default_version
```
and seems like it is not able to deal with a version number with more than one '.'

**Comment by ashishp166** [comment]
Yeah, facing the same issue. I just decided to use the colmap2nerf.py instead, but now just not able to get a lot of overlap in the images.

**Comment by liu-bohan** [comment]
my brute-force solution is: edit the `get_colmap_version( )` function in _colmap_utils.py_ file. change `return float(version)` to `return float("3.9")`

> Yeah, facing the same issue. I just decided to use the colmap2nerf.py instead, but now just not able to get a lot of overlap in the images.

**Comment by sarlinpe** [comment]
This issue is not related to COLMAP but to nerfstudio. It has already been fixed there: https://github.com/nerfstudio-project/nerfstudio/commit/3db08019db59aa88c904e8c1c03dff909857c05a
