### ISSUE TITLE
Segmentation Fault After Iterating Over Images in Reconstruction Class

### ISSUE THREAD

**Issue by botat21** [colmap/colmap#2795]
**Description:**
I am encountering a Segmentation fault error while using the scantools.run_reference_rendering.py script from the lamar repository. The error seems to occur inconsistently at different points in the code, but always after iterating over reconstruction.images.values() and attempting to exit the loop.

**Example:**
Here, I have 376 images in my session.

###### Code snippet:
```python
count = 0
for im in rec.images.values():
    
count = count + 1
    print('image ', count)
    cam = rec.cameras[im.camera_id]
    for p in im.points2D:
        if p.has_point3D():
            cost = pyceres.factors.BundleAdjustmentCost(cam.model_id, p.xy, im.qvec, im.tvec)
            prob.add_residual_block(cost, loss, [rec.points3D[p.point3D_id].xyz, cam.params])   
print('loop exited') 
```

###### Output:
...
image  370
image  371
image  372
image  373
image  374
image  375
image  376
Aborted (core dumped)

###### Debugger output:
```
Thread 1 "python" received signal SIGSEGV, Segmentation fault.
0x00007fd7ddbd71a0 in ?? () from /lib/x86_64-linux-gnu/libgcc_s.so.1
(gdb) bt
#0  0x00007fd7ddbd71a0 in ?? () from /lib/x86_64-linux-gnu/libgcc_s.so.1
#1  0x00007fd7ddbd735f in __gcc_personality_v0 () from /lib/x86_64-linux-gnu/libgcc_s.so.1
#2  0x00007fd66220ee5b in __libunwind_Unwind_RaiseException () from /lib/x86_64-linux-gnu/libunwind.so.8
#3  0x00007fd6620864cb in __cxa_throw () from /lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007fd65ff65b75 in ?? () from /usr/local/lib/python3.10/dist-packages/pycolmap.cpython-310-x86_64-linux-gnu.so
#5  0x00007fd65ffb42f8 in ?? () from /usr/local/lib/python3.10/dist-packages/pycolmap.cpython-310-x86_64-linux-gnu.so
#6  0x000056521b2a2dae in ?? ()
#7  0x000056521b29952b in _PyObject_MakeTpCall ()
#8  0x000056521b2b152b in ?? ()
#9  0x000056521b30bbf1 in ?? ()
#10 0x000056521b3d5543 in ?? ()
#11 0x000056521b28bd24 in _PyEval_EvalFrameDefault ()
#12 0x000056521b2a36ac in _PyFunction_Vectorcall ()
#13 0x000056521b28b935 in _PyEval_EvalFrameDefault ()
#14 0x000056521b2a36ac in _PyFunction_Vectorcall ()
#15 0x000056521b28b935 in _PyEval_EvalFrameDefault ()
#16 0x000056521b2a36ac in _PyFunction_Vectorcall ()
#17 0x000056521b2b1f02 in PyObject_Call ()
#18 0x000056521b28dca9 in _PyEval_EvalFrameDefault ()
#19 0x000056521b288096 in ?? ()
#20 0x000056521b37df66 in PyEval_EvalCode ()
#21 0x000056521b383a2d in ?? ()
#22 0x000056521b2a3909 in ?? ()
#23 0x000056521b28b935 in _PyEval_EvalFrameDefault ()
#24 0x000056521b2a36ac in _PyFunction_Vectorcall ()
#25 0x000056521b28b935 in _PyEval_EvalFrameDefault ()
#26 0x000056521b2a36ac in _PyFunction_Vectorcall ()
#27 0x000056521b39bb7d in ?? ()
#28 0x000056521b39a578 in Py_RunMain ()
#29 0x000056521b370dfd in Py_BytesMain ()
#30 0x00007fd7e087dd90 in __libc_start_call_main (main=main@entry=0x56521b370dc0, argc=argc@entry=7, argv=argv@entry=0x7ffe97ca1518)
    at ../sysdeps/nptl/libc_start_call_main.h:58
#31 0x00007fd7e087de40 in __libc_start_main_impl (main=0x56521b370dc0, argc=7, argv=0x7ffe97ca1518, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>,
    stack_end=0x7ffe97ca1508) at ../csu/libc-start.c:392
#32 0x000056521b370cf5 in _start ()
```

**Environment:**
- OS: Ubuntu 20.04.6 LTS
- COLMAP Version: 3.8 (built from source)
- PyCOLMAP Version: 0.4.0 (Note: I could not run any lamar script with 0.6.0, but this one worked with everything else)
- Capture Device: NavVis M6

**Comment by Tony-Hou** [comment]
How to run gdb?  How to config the cmakelist.txt?
