### ISSUE TITLE
Install pycolmap from source failed in WSL environment

### ISSUE THREAD

**Issue by BridgetteGao** [colmap/colmap#2839]
python -m pip install ./pycolmap/
Looking in indexes: https://mirrors.tuna.tsinghua.edu.cn/pypi/web/simple
Processing ./pycolmap
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting numpy (from pycolmap==3.11.0.dev0)
  Using cached https://mirrors.tuna.tsinghua.edu.cn/pypi/web/packages/b9/14/78635daab4b07c0930c919d451b8bf8c164774e6a3413aed04a6d95758ce/numpy-2.0.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (19.5 MB)
Building wheels for collected packages: pycolmap
  Building wheel for pycolmap (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for pycolmap (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [171 lines of output]
      WARNING: Minimum CMake version set as 'CMakeLists.txt' is less than 3.15. This is not supported by scikit-build-core; set manually or increase to avoid this warning.
      *** scikit-build-core 0.10.7 using CMake 3.22.1 (wheel)
      2024-10-16 16:05:38,141 - scikit_build_core - WARNING - No license files found, set wheel.license-files to [] to suppress this warning
      *** Configuring CMake...
      loading initial cache file /tmp/tmpv3s_t_0m/build/CMakeInit.txt
      -- The C compiler identification is GNU 11.4.0
      -- The CXX compiler identification is GNU 11.4.0
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /usr/bin/gcc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /usr/bin/g++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.74.0/BoostConfig.cmake (found version "1.74.0") found components: graph program_options system
      -- Found FreeImage
      --   Includes : /usr/include
      --   Libraries : /usr/lib/x86_64-linux-gnu/libfreeimage.so
      -- Found FLANN
      --   Includes : /usr/include
      --   Libraries : /usr/lib/x86_64-linux-gnu/libflann.so
      -- Found LZ4
      --   Includes : /usr/include
      --   Libraries : /usr/lib/x86_64-linux-gnu/liblz4.so
      -- Found Metis
      --   Includes : /usr/include
      --   Libraries : /usr/lib/x86_64-linux-gnu/libmetis.so
      -- Found Glog
      --   Target : glog::glog
      -- Found SQLite3: /usr/include (found version "3.37.2")
      -- Found OpenGL: /usr/lib/x86_64-linux-gnu/libGL.so
      -- Found Glew
      --   Includes : /usr/include
      --   Libraries : /usr/lib/x86_64-linux-gnu/libGLEW.so
      -- Found Git: /usr/bin/git (found version "2.34.1")
      -- Looking for pthread.h
      -- Looking for pthread.h - found
      -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
      -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
      -- Found Threads: TRUE
      -- Found required Ceres dependency: Eigen version 3.4.0 in /usr/include/eigen3
      -- Found required Ceres dependency: glog
      -- Found required Ceres dependency: gflags
      -- Found Ceres version: 2.0.0 installed in: /usr with components: [EigenSparse, SparseLinearAlgebraLibrary, LAPACK, SuiteSparse, CXSparse, SchurSpecializations, Multithreading]
      -- Enabling OpenMP support
      -- Using header-only CGAL
      -- Targetting Ninja
      -- Using /usr/bin/g++ compiler.
      -- Found GMP: /usr/lib/x86_64-linux-gnu/libgmp.so
      -- Found MPFR: /usr/lib/x86_64-linux-gnu/libmpfr.so
      -- Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.74.0/BoostConfig.cmake (found suitable version "1.74.0", minimum required is "1.48")
      -- Boost include dirs: /usr/include
      -- Boost libraries:
      -- Using gcc version 4 or later. Adding -frounding-math
      -- Found CGAL
      --   Includes : /usr/include
      --   Libraries : CGAL
      -- The CUDA compiler identification is NVIDIA 11.5.119
      -- Detecting CUDA compiler ABI info
      -- Detecting CUDA compiler ABI info - done
      -- Check for working CUDA compiler: /usr/bin/nvcc - skipped
      -- Detecting CUDA compile features
      -- Detecting CUDA compile features - done
      -- Enabling CUDA support (version: 11.5.119, archs: 80)
      -- Found Qt
      --   Module : /usr/lib/x86_64-linux-gnu/cmake/Qt5Core
      --   Module : /usr/lib/x86_64-linux-gnu/cmake/Qt5OpenGL
      --   Module : /usr/lib/x86_64-linux-gnu/cmake/Qt5Widgets
      -- Enabling GUI support
      -- Disabling OpenGL support
      -- Enabling GPU support (OpenGL: , CUDA: ON)
      -- Found Python: /home/bridgette/miniconda3/envs/pycolmap/bin/python (found version "3.9.0") found components: Interpreter Development.Module
      -- Performing Test HAS_FLTO
      -- Performing Test HAS_FLTO - Success
      -- Found pybind11: /tmp/pip-build-env-rm6loqgc/overlay/lib/python3.9/site-packages/pybind11/include (found version "2.13.0")
      -- Enabling stubs generation
      -- Configuring done
      -- Generating done
      -- Build files have been written to: /tmp/tmpv3s_t_0m/build
      *** Building project with Ninja...
      [1/42] Building CXX object CMakeFiles/_core.dir/home/bridgette/pycolmap/colmap/src/pycolmap/estimators/bindings.cc.o
      [2/42] Building CXX object CMakeFiles/_core.dir/home/bridgette/pycolmap/colmap/src/pycolmap/pipeline/bindings.cc.o
      [3/42] Building CXX object CMakeFiles/_core.dir/home/bridgette/pycolmap/colmap/src/pycolmap/estimators/homography_matrix.cc.o
      [4/42] Building CXX object CMakeFiles/_core.dir/home/bridgette/pycolmap/colmap/src/pycolmap/geometry/homography_matrix.cc.o
      [5/42] Building CXX object CMakeFiles/_core.dir/home/bridgette/pycolmap/colmap/src/pycolmap/estimators/manifold.cc.o
      [6/42] Building CXX object CMakeFiles/_core.dir/home/bridgette/pycolmap/colmap/src/pycolmap/main.cc.o
      [7/42] Building CXX object CMakeFiles/_core.dir/home/bridgette/pycolmap/colmap/src/pycolmap/optim/bindings.cc.o
      [8/42] Building CXX object CMakeFiles/_core.dir/home/bridgette/pycolmap/colmap/src/pycolmap/estimators/fundamental_matrix.cc.o
      [9/42] Building CXX object CMakeFiles/_core.dir/home/bridgette/pycolmap/colmap/src/pycolmap/estimators/alignment.cc.o
      [10/42] Building CXX object CMakeFiles/_core.dir/home/bridgette/pycolmap/colmap/src/pycolmap/estimators/covariance.cc.o
      [11/42] Building CXX object CMakeFiles/_core.dir/home/bridgette/pycolmap/colmap/src/pycolmap/pipeline/extract_features.cc.o
      [12/42] Building CXX object CMakeFiles/_core.dir/home/bridgette/pycolmap/colmap/src/pycolmap/estimators/essential_matrix.cc.o
      [13/42] Building CXX object CMakeFiles/_core.dir/home/bridgette/pycolmap/colmap/src/pycolmap/estimators/generalized_absolute_pose.cc.o
      [14/42] Building CXX object CMakeFiles/_core.dir/home/bridgette/pycolmap/colmap/src/pycolmap/pipeline/meshing.cc.o
      [15/42] Building CXX object CMakeFiles/_core.dir/home/bridgette/pycolmap/colmap/src/pycolmap/estimators/two_view_geometry.cc.o
      [16/42] Building CXX object CMakeFiles/_core.dir/home/bridgette/pycolmap/colmap/src/pycolmap/scene/bindings.cc.o
      [17/42] Building CXX object CMakeFiles/_core.dir/home/bridgette/pycolmap/colmap/src/pycolmap/estimators/absolute_pose.cc.o
      [18/42] Building CXX object CMakeFiles/_core.dir/home/bridgette/pycolmap/colmap/src/pycolmap/pipeline/images.cc.o
      [19/42] Building CXX object CMakeFiles/_core.dir/home/bridgette/pycolmap/colmap/src/pycolmap/estimators/triangulation.cc.o
      [20/42] Building CXX object CMakeFiles/_core.dir/home/bridgette/pycolmap/colmap/src/pycolmap/feature/sift.cc.o
      [21/42] Building CXX object CMakeFiles/_core.dir/home/bridgette/pycolmap/colmap/src/pycolmap/geometry/bindings.cc.o
      [22/42] Building CXX object CMakeFiles/_core.dir/home/bridgette/pycolmap/colmap/src/pycolmap/estimators/bundle_adjustment.cc.o
      [23/42] Building CXX object CMakeFiles/_core.dir/home/bridgette/pycolmap/colmap/src/pycolmap/sfm/bindings.cc.o
      [24/42] Building CXX object CMakeFiles/_core.dir/home/bridgette/pycolmap/colmap/src/pycolmap/scene/database.cc.o
      [25/42] Building CXX object CMakeFiles/_core.dir/home/bridgette/pycolmap/colmap/src/pycolmap/scene/correspondence_graph.cc.o
      [26/42] Building CXX object CMakeFiles/_core.dir/home/bridgette/pycolmap/colmap/src/pycolmap/scene/database_cache.cc.o
      [27/42] Building CXX object CMakeFiles/_core.dir/home/bridgette/pycolmap/colmap/src/pycolmap/pipeline/mvs.cc.o
      [28/42] Building CXX object CMakeFiles/_core.dir/home/bridgette/pycolmap/colmap/src/pycolmap/scene/track.cc.o
      [29/42] Building CXX object CMakeFiles/_core.dir/home/bridgette/pycolmap/colmap/src/pycolmap/pipeline/sfm.cc.o
      [30/42] Building CXX object CMakeFiles/_core.dir/home/bridgette/pycolmap/colmap/src/pycolmap/scene/reconstruction_manager.cc.o
      [31/42] Building CXX object CMakeFiles/_core.dir/home/bridgette/pycolmap/colmap/src/pycolmap/scene/camera.cc.o
      [32/42] Building CXX object CMakeFiles/_core.dir/home/bridgette/pycolmap/colmap/src/pycolmap/scene/reconstruction.cc.o
      [33/42] Building CXX object CMakeFiles/_core.dir/home/bridgette/pycolmap/colmap/src/pycolmap/scene/point2d.cc.o
      [34/42] Building CXX object CMakeFiles/_core.dir/home/bridgette/pycolmap/colmap/src/pycolmap/pipeline/match_features.cc.o
      [35/42] Building CXX object CMakeFiles/_core.dir/home/bridgette/pycolmap/colmap/src/pycolmap/scene/image.cc.o
      [36/42] Building CXX object CMakeFiles/_core.dir/home/bridgette/pycolmap/colmap/src/pycolmap/scene/point3d.cc.o
      [37/42] Building CXX object CMakeFiles/_core.dir/home/bridgette/pycolmap/colmap/src/pycolmap/sfm/observation_manager.cc.o
      [38/42] Building CXX object CMakeFiles/_core.dir/home/bridgette/pycolmap/colmap/src/pycolmap/scene/two_view_geometry.cc.o
      [39/42] Building CXX object CMakeFiles/_core.dir/home/bridgette/pycolmap/colmap/src/pycolmap/sfm/incremental_triangulator.cc.o
      [40/42] Building CXX object CMakeFiles/_core.dir/home/bridgette/pycolmap/colmap/src/pycolmap/sfm/incremental_mapper.cc.o
      [41/42] Building CXX object CMakeFiles/_core.dir/home/bridgette/pycolmap/colmap/src/pycolmap/estimators/cost_functions.cc.o
      [42/42] Linking CXX shared module _core.cpython-39-x86_64-linux-gnu.so
      FAILED: _core.cpython-39-x86_64-linux-gnu.so
      : && /usr/bin/g++  -pthread -B /home/bridgette/miniconda3/envs/pycolmap/compiler_compat -Wl,--sysroot=/ -fPIC -O3 -DNDEBUG  -flto -shared  -o _core.cpython-39-x86_64-linux-gnu.so CMakeFiles/_core.dir/home/bridgette/pycolmap/colmap/src/pycolmap/estimators/absolute_pose.cc.o CMakeFiles/_core.dir/home/bridgette/pycolmap/colmap/src/pycolmap/estimators/alignment.cc.o CMakeFiles/_core.dir/home/bridgette/pycolmap/colmap/src/pycolmap/estimators/bindings.cc.o CMakeFiles/_core.dir/home/bridgette/pycolmap/colmap/src/pycolmap/estimators/bundle_adjustment.cc.o CMakeFiles/_core.dir/home/bridgette/pycolmap/colmap/src/pycolmap/estimators/cost_functions.cc.o CMakeFiles/_core.dir/home/bridgette/pycolmap/colmap/src/pycolmap/estimators/covariance.cc.o CMakeFiles/_core.dir/home/bridgette/pycolmap/colmap/src/pycolmap/estimators/essential_matrix.cc.o CMakeFiles/_core.dir/home/bridgette/pycolmap/colmap/src/pycolmap/estimators/fundamental_matrix.cc.o CMakeFiles/_core.dir/home/bridgette/pycolmap/colmap/src/pycolmap/estimators/generalized_absolute_pose.cc.o CMakeFiles/_core.dir/home/bridgette/pycolmap/colmap/src/pycolmap/estimators/homography_matrix.cc.o CMakeFiles/_core.dir/home/bridgette/pycolmap/colmap/src/pycolmap/estimators/manifold.cc.o CMakeFiles/_core.dir/home/bridgette/pycolmap/colmap/src/pycolmap/estimators/triangulation.cc.o CMakeFiles/_core.dir/home/bridgette/pycolmap/colmap/src/pycolmap/estimators/two_view_geometry.cc.o CMakeFiles/_core.dir/home/bridgette/pycolmap/colmap/src/pycolmap/feature/sift.cc.o CMakeFiles/_core.dir/home/bridgette/pycolmap/colmap/src/pycolmap/geometry/bindings.cc.o CMakeFiles/_core.dir/home/bridgette/pycolmap/colmap/src/pycolmap/geometry/homography_matrix.cc.o CMakeFiles/_core.dir/home/bridgette/pycolmap/colmap/src/pycolmap/main.cc.o CMakeFiles/_core.dir/home/bridgette/pycolmap/colmap/src/pycolmap/optim/bindings.cc.o CMakeFiles/_core.dir/home/bridgette/pycolmap/colmap/src/pycolmap/pipeline/bindings.cc.o CMakeFiles/_core.dir/home/bridgette/pycolmap/colmap/src/pycolmap/pipeline/extract_features.cc.o CMakeFiles/_core.dir/home/bridgette/pycolmap/colmap/src/pycolmap/pipeline/images.cc.o CMakeFiles/_core.dir/home/bridgette/pycolmap/colmap/src/pycolmap/pipeline/match_features.cc.o CMakeFiles/_core.dir/home/bridgette/pycolmap/colmap/src/pycolmap/pipeline/meshing.cc.o CMakeFiles/_core.dir/home/bridgette/pycolmap/colmap/src/pycolmap/pipeline/mvs.cc.o CMakeFiles/_core.dir/home/bridgette/pycolmap/colmap/src/pycolmap/pipeline/sfm.cc.o CMakeFiles/_core.dir/home/bridgette/pycolmap/colmap/src/pycolmap/scene/bindings.cc.o CMakeFiles/_core.dir/home/bridgette/pycolmap/colmap/src/pycolmap/scene/camera.cc.o CMakeFiles/_core.dir/home/bridgette/pycolmap/colmap/src/pycolmap/scene/correspondence_graph.cc.o CMakeFiles/_core.dir/home/bridgette/pycolmap/colmap/src/pycolmap/scene/database.cc.o CMakeFiles/_core.dir/home/bridgette/pycolmap/colmap/src/pycolmap/scene/database_cache.cc.o CMakeFiles/_core.dir/home/bridgette/pycolmap/colmap/src/pycolmap/scene/image.cc.o CMakeFiles/_core.dir/home/bridgette/pycolmap/colmap/src/pycolmap/scene/point2d.cc.o CMakeFiles/_core.dir/home/bridgette/pycolmap/colmap/src/pycolmap/scene/point3d.cc.o CMakeFiles/_core.dir/home/bridgette/pycolmap/colmap/src/pycolmap/scene/reconstruction.cc.o CMakeFiles/_core.dir/home/bridgette/pycolmap/colmap/src/pycolmap/scene/reconstruction_manager.cc.o CMakeFiles/_core.dir/home/bridgette/pycolmap/colmap/src/pycolmap/scene/track.cc.o CMakeFiles/_core.dir/home/bridgette/pycolmap/colmap/src/pycolmap/scene/two_view_geometry.cc.o CMakeFiles/_core.dir/home/bridgette/pycolmap/colmap/src/pycolmap/sfm/bindings.cc.o CMakeFiles/_core.dir/home/bridgette/pycolmap/colmap/src/pycolmap/sfm/incremental_mapper.cc.o CMakeFiles/_core.dir/home/bridgette/pycolmap/colmap/src/pycolmap/sfm/incremental_triangulator.cc.o CMakeFiles/_core.dir/home/bridgette/pycolmap/colmap/src/pycolmap/sfm/observation_manager.cc.o -L/usr/lib/x86_64-linux-gnu/stubs /usr/local/lib/libcolmap_exe.a  /usr/local/lib/libcolmap_ui.a  /usr/local/lib/libcolmap_controllers.a  /usr/local/lib/libcolmap_feature.a  /usr/local/lib/libcolmap_retrieval.a  /usr/lib/x86_64-linux-gnu/libflann.so  /usr/lib/x86_64-linux-gnu/liblz4.so  /usr/local/lib/libcolmap_sfm.a  /usr/local/lib/libcolmap_estimators.a  /usr/local/lib/libcolmap_optim.a  /usr/local/lib/libPoseLib.a  /usr/lib/x86_64-linux-gnu/libboost_program_options.so.1.74.0  /usr/local/lib/libcolmap_mvs_cuda.a  /usr/local/lib/libcolmap_mvs.a  /usr/local/lib/libcolmap_image.a  /usr/local/lib/libcolmap_lsd.a  /usr/local/lib/libcolmap_scene.a  /usr/local/lib/libcolmap_feature_types.a  /usr/local/lib/libcolmap_geometry.a  /usr/local/lib/libcolmap_math.a  /usr/lib/x86_64-linux-gnu/libmetis.so  /usr/lib/x86_64-linux-gnu/libboost_graph.so.1.74.0  /usr/lib/x86_64-linux-gnu/libboost_regex.so.1.74.0  /usr/local/lib/libcolmap_sensor.a  /usr/lib/libceres.so.2.0.0  /usr/local/lib/libcolmap_vlfeat.a  /usr/lib/x86_64-linux-gnu/libfreeimage.so  /usr/local/lib/libcolmap_poisson_recon.a  /usr/lib/gcc/x86_64-linux-gnu/11/libgomp.so  /usr/lib/x86_64-linux-gnu/libgmpxx.so  /usr/lib/x86_64-linux-gnu/libmpfr.so  /usr/lib/x86_64-linux-gnu/libgmp.so  /usr/local/lib/libcolmap_util_cuda.a  /usr/local/lib/libcolmap_util.a  /usr/lib/x86_64-linux-gnu/libglog.so.0.4.0  /usr/lib/x86_64-linux-gnu/libunwind.so  /usr/lib/x86_64-linux-gnu/libgflags.so.2.2.2  -lpthread  /usr/lib/x86_64-linux-gnu/libsqlite3.so  /usr/lib/x86_64-linux-gnu/libQt5OpenGL.so.5.15.3  /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5.15.3  /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5.15.3  /usr/lib/x86_64-linux-gnu/libQt5Core.so.5.15.3  /usr/local/lib/libcolmap_sift_gpu.a  /usr/lib/x86_64-linux-gnu/libGL.so  /usr/lib/x86_64-linux-gnu/libcudart.so  /usr/lib/x86_64-linux-gnu/libcurand.so  /usr/lib/x86_64-linux-gnu/libGLEW.so  -lcudadevrt  -lcudart_static  -lrt  -ldl && cd /tmp/tmpv3s_t_0m/build && /usr/bin/strip /tmp/tmpv3s_t_0m/build/_core.cpython-39-x86_64-linux-gnu.so && cd /tmp/tmpv3s_t_0m/build && /usr/bin/cmake -E env PYTHONPATH=/tmp/tmpv3s_t_0m/build:/tmp/pip-build-env-rm6loqgc/site bash /home/bridgette/pycolmap/colmap/pycolmap/generate_stubs.sh /home/bridgette/miniconda3/envs/pycolmap/bin/python /tmp/tmpv3s_t_0m/build
      /home/bridgette/pycolmap/colmap/pycolmap/../src/pycolmap/pybind11_extension.h:30:8: warning: type ‘struct type_caster’ violates the C++ One Definition Rule [-Wodr]
         30 | struct type_caster<std::string> {
            |        ^
      /tmp/pip-build-env-rm6loqgc/overlay/lib/python3.9/site-packages/pybind11/include/pybind11/cast.h:517:8: note: a type with different bases is defined in another translation unit
        517 | struct type_caster<std::basic_string<CharT, Traits, Allocator>,
            |        ^
      /home/bridgette/pycolmap/colmap/pycolmap/../src/pycolmap/pybind11_extension.h:30:8: note: type ‘struct type_caster’ itself violates the C++ One Definition Rule
         30 | struct type_caster<std::string> {
            |        ^
      /tmp/pip-build-env-rm6loqgc/overlay/lib/python3.9/site-packages/pybind11/include/pybind11/cast.h:517:8: note: the incompatible type is defined here
        517 | struct type_caster<std::basic_string<CharT, Traits, Allocator>,
            |        ^
      /usr/include/c++/11/tuple:981:11: note: type ‘struct tuple’ itself violates the C++ One Definition Rule
        981 |     class tuple<_T1, _T2> : public _Tuple_impl<0, _T1, _T2>
            |           ^
      /usr/include/c++/11/tuple:981: note: the incompatible type is defined here
        981 |     class tuple<_T1, _T2> : public _Tuple_impl<0, _T1, _T2>
            |
      lto-wrapper: warning: using serial compilation of 86 LTRANS jobs
      Building stubs with /home/bridgette/miniconda3/envs/pycolmap/bin/python to /tmp/tmpv3s_t_0m/build
      Traceback (most recent call last):
        File "/home/bridgette/miniconda3/envs/pycolmap/lib/python3.9/runpy.py", line 197, in _run_module_as_main
          return _run_code(code, main_globals, None,
        File "/home/bridgette/miniconda3/envs/pycolmap/lib/python3.9/runpy.py", line 87, in _run_code
          exec(code, run_globals)
        File "/tmp/pip-build-env-rm6loqgc/overlay/lib/python3.9/site-packages/pybind11_stubgen/__main__.py", line 4, in <module>
          main()
        File "/tmp/pip-build-env-rm6loqgc/overlay/lib/python3.9/site-packages/pybind11_stubgen/__init__.py", line 319, in main
          run(
        File "/tmp/pip-build-env-rm6loqgc/overlay/lib/python3.9/site-packages/pybind11_stubgen/__init__.py", line 358, in run
          QualifiedName.from_str(module_name), importlib.import_module(module_name)
        File "/home/bridgette/miniconda3/envs/pycolmap/lib/python3.9/importlib/__init__.py", line 127, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
        File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
        File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
        File "<frozen importlib._bootstrap>", line 565, in module_from_spec
        File "<frozen importlib._bootstrap_external>", line 1108, in create_module
        File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
      ImportError: /home/bridgette/miniconda3/envs/pycolmap/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /tmp/tmpv3s_t_0m/build/_core.cpython-39-x86_64-linux-gnu.so)
      ninja: build stopped: subcommand failed.

      *** CMake build failed
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pycolmap
Failed to build pycolmap
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (pycolmap)、

os: ubuntu 22.04
python 3.9

**Comment by sarlinpe** [comment]
It's unclear to me why the stubgen fails, but you can safely disable it using:
```bash
python -m pip install ./pycolmap/ --cmake.define.GENERATE_STUBS=OFF
```

**Comment by AmyPhung** [comment]
I also got this same stubgen issue on a local install of ubuntu 22.04 with python 3.10. I needed to upgrade pip to 24.3 and needed to add "config-settings" to the options. The command that worked for me was
```
 python3 -m pip install ./pycolmap/ --config-settings=cmake.define.GENERATE_STUBS=OFF
```

**Comment by AmyPhung** [comment]
Although that command got the pip install to work for me, it resulted in the following error when importing the package in python:
```
local/lib/python3.10/site-packages/pycolmap/_core.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZTVN5ceres31EigenQuaternionParameterizationE
```

Using the release version that matched my python version (3.10) seemed to fix the issue

**Comment by ahojnnes** [comment]
Closing: pycolmap install resolved; GENERATE_STUBS=OFF workaround.
