### ISSUE TITLE
Segmentation fault when doing dense reconstruction, stereo step

### ISSUE THREAD

**Issue by andrejpan** [colmap/colmap#42]
Here is my gdb trace:

```
pangerca@lapcremers29:/work/pangerca$ gdb ./colmap/build/src/exe/colmap                                   
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./colmap/build/src/exe/colmap...done.
(gdb) r
Starting program: /work/pangerca/colmap/build/src/exe/colmap 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffea2fb700 (LWP 7957)]
[New Thread 0x7fffe9afa700 (LWP 7958)]
[New Thread 0x7fffe72f9700 (LWP 7959)]
[New Thread 0x7fffe4af8700 (LWP 7960)]
[New Thread 0x7fffe22f7700 (LWP 7961)]
[New Thread 0x7fffdfaf6700 (LWP 7962)]
[New Thread 0x7fffdd2f5700 (LWP 7963)]
[New Thread 0x7fffd4de1700 (LWP 7964)]
[New Thread 0x7fffc6162700 (LWP 7966)]
[New Thread 0x7fffc5961700 (LWP 7967)]
[New Thread 0x7fffc5160700 (LWP 7968)]
[New Thread 0x7fffc495f700 (LWP 7969)]
[Thread 0x7fffc5160700 (LWP 7968) exited]
[New Thread 0x7fffc5160700 (LWP 7970)]
[New Thread 0x7fffaad2a700 (LWP 7971)]
[Thread 0x7fffaad2a700 (LWP 7971) exited]
[Thread 0x7fffc495f700 (LWP 7969) exited]
[New Thread 0x7fffc495f700 (LWP 7972)]
[Thread 0x7fffc5160700 (LWP 7970) exited]
** (colmap:7953): WARNING **: Index value is too large
[New Thread 0x7fffc5160700 (LWP 7973)]
[New Thread 0x7fffaad2a700 (LWP 7974)]
[New Thread 0x7fffa8f28700 (LWP 7975)]
[New Thread 0x7fffa3fff700 (LWP 7976)]
[New Thread 0x7fffa37fe700 (LWP 7977)]
[New Thread 0x7fffa2ffd700 (LWP 7978)]
[New Thread 0x7fffa27fc700 (LWP 7979)]
[New Thread 0x7fffa1ffb700 (LWP 7980)]
[New Thread 0x7fffa17fa700 (LWP 7981)]
[Thread 0x7fffa2ffd700 (LWP 7978) exited]
[Thread 0x7fffa37fe700 (LWP 7977) exited]
[Thread 0x7fffaad2a700 (LWP 7974) exited]
[Thread 0x7fffa17fa700 (LWP 7981) exited]
[Thread 0x7fffa1ffb700 (LWP 7980) exited]
[Thread 0x7fffa27fc700 (LWP 7979) exited]
[Thread 0x7fffa3fff700 (LWP 7976) exited]
[Thread 0x7fffa8f28700 (LWP 7975) exited]
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff5816ddb in hb_qt_get_unicode_funcs() () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
(gdb) bt
#0  0x00007ffff5816ddb in hb_qt_get_unicode_funcs() () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#1  0x00007ffff577431b in QTextEngine::shapeTextWithHarfbuzzNG(QScriptItem const&, unsigned short const*, int, QFontEngine*, QVector<unsigned int> const&, bool) const ()
   from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#2  0x00007ffff5777b1d in QTextEngine::shapeText(int) const ()
   from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#3  0x00007ffff57781e5 in QTextEngine::shape(int) const () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#4  0x00007ffff578a882 in QTextLine::layout_helper(int) () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#5  0x00007ffff578babb in QTextLine::setLineWidth(double) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#6  0x00007ffff668ba33 in QPlainTextDocumentLayout::layoutBlock(QTextBlock const&) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#7  0x00007ffff668bd93 in QPlainTextDocumentLayout::blockBoundingRect(QTextBlock const&) const ()
   from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#8  0x00007ffff668e84f in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#9  0x00007ffff6e322a6 in QMetaObject::activate(QObject*, int, int, void**) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#10 0x00007ffff666f415 in QWidgetTextControl::documentSizeChanged(QSizeF const&) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#11 0x00007ffff6677039 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#12 0x00007ffff6e322a6 in QMetaObject::activate(QObject*, int, int, void**) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#13 0x00007ffff57b60c5 in QAbstractTextDocumentLayout::documentSizeChanged(QSizeF const&) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#14 0x00007ffff668c1d2 in QPlainTextDocumentLayout::documentChanged(int, int, int) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#15 0x00007ffff57a77ea in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#16 0x00007ffff57cefb0 in QTextCursor::insertText(QString const&, QTextCharFormat const&) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#17 0x00007ffff57cf6b4 in QTextCursor::insertText(QString const&) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#18 0x00000000005cca84 in colmap::LogWidget::Flush (this=0x23415e0)
    at /work/pangerca/colmap/src/ui/log_widget.cc:102
#19 0x00007ffff6e31d73 in QMetaObject::activate(QObject*, int, int, void**) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#20 0x00007ffff6e3e622 in QTimer::timerEvent(QTimerEvent*) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#21 0x00007ffff6e33054 in QObject::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#22 0x00007ffff64b4c8c in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#23 0x00007ffff64b9e56 in QApplication::notify(QObject*, QEvent*) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#24 0x00007ffff6e0ac2d in QCoreApplication::notifyInternal(QObject*, QEvent*) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#25 0x00007ffff6e571ad in QTimerInfoList::activateTimers() ()
   from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#26 0x00007ffff6e57661 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#27 0x00007ffff130de04 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#28 0x00007ffff130e048 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#29 0x00007ffff130e0ec in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#30 0x00007ffff6e5798c in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#31 0x00007ffff6e0996b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#32 0x00007ffff6e100e1 in QCoreApplication::exec() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#33 0x0000000000578ca3 in main (argc=1, argv=<optimized out>)
    at /work/pangerca/colmap/src/exe/colmap.cc:49
```

Would you also need my sparse model?

**Comment by andrejpan** [comment]
Another set, new error at the same step.
```
(gdb) r
Starting program: /work/pangerca/colmap/build/src/exe/colmap 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffea2fb700 (LWP 6700)]
[New Thread 0x7fffe9afa700 (LWP 6701)]
[New Thread 0x7fffe72f9700 (LWP 6702)]
[New Thread 0x7fffe4af8700 (LWP 6703)]
[New Thread 0x7fffe22f7700 (LWP 6704)]
[New Thread 0x7fffdfaf6700 (LWP 6705)]
[New Thread 0x7fffdd2f5700 (LWP 6706)]
[New Thread 0x7fffd4de1700 (LWP 6707)]
[New Thread 0x7fffc6162700 (LWP 6709)]
[New Thread 0x7fffc5961700 (LWP 6710)]
[New Thread 0x7fffc5160700 (LWP 6711)]
[New Thread 0x7fffc495f700 (LWP 6712)]
Problem creating accessible interface for:  QWindow(0x1ce7e20) 
Make sure to deploy Qt with accessibility plugins. 
[Thread 0x7fffc5160700 (LWP 6711) exited]
[New Thread 0x7fffc5160700 (LWP 6744)]
[New Thread 0x7fffaaefd700 (LWP 6745)]
[Thread 0x7fffaaefd700 (LWP 6745) exited]
[Thread 0x7fffc5160700 (LWP 6744) exited]
[New Thread 0x7fffc5160700 (LWP 6750)]
[Thread 0x7fffc5160700 (LWP 6750) exited]
[New Thread 0x7fffc5160700 (LWP 6768)]
[New Thread 0x7fffaaefd700 (LWP 6769)]
[Thread 0x7fffc5160700 (LWP 6768) exited]
[Thread 0x7fffaaefd700 (LWP 6769) exited]
[New Thread 0x7fffaaefd700 (LWP 6793)]
[Thread 0x7fffaaefd700 (LWP 6793) exited]
[New Thread 0x7fffaaefd700 (LWP 6813)]
[New Thread 0x7fffc5160700 (LWP 6814)]
[Thread 0x7fffc495f700 (LWP 6712) exited]
[Thread 0x7fffaaefd700 (LWP 6813) exited]
[New Thread 0x7fffaaefd700 (LWP 6858)]
[New Thread 0x7fffc495f700 (LWP 6890)]
[New Thread 0x7fffaa3ef700 (LWP 6891)]
[New Thread 0x7fffa9bee700 (LWP 6892)]
[New Thread 0x7fffa93ed700 (LWP 6893)]
[New Thread 0x7fffa8bec700 (LWP 6894)]
[New Thread 0x7fff8bfff700 (LWP 6895)]
[New Thread 0x7fff8b7fe700 (LWP 6896)]
[New Thread 0x7fff8affd700 (LWP 6897)]
[Thread 0x7fffa9bee700 (LWP 6892) exited]
[Thread 0x7fffa8bec700 (LWP 6894) exited]
[Thread 0x7fff8bfff700 (LWP 6895) exited]
[Thread 0x7fffa93ed700 (LWP 6893) exited]
[Thread 0x7fffaa3ef700 (LWP 6891) exited]
[Thread 0x7fff8b7fe700 (LWP 6896) exited]
[Thread 0x7fffc495f700 (LWP 6890) exited]
[Thread 0x7fff8affd700 (LWP 6897) exited]

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff572e750 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
(gdb) bt
#0  0x00007ffff572e750 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#1  0x00007ffff572d6ea in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#2  0x00007ffff572d7df in QPixmapCache::find(QString const&, QPixmap*) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5
#3  0x00007ffff658af25 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#4  0x00007ffff6584779 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#5  0x00007ffff6534388 in QCommonStyle::drawControl(QStyle::ControlElement, QStyleOption const*, QPainter*, QWidget const*) const () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#6  0x00007ffff65854c5 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#7  0x00007ffff6632c3a in QProgressBar::paintEvent(QPaintEvent*) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#8  0x00007ffff64f0302 in QWidget::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#9  0x00007ffff663364f in QProgressBar::event(QEvent*) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#10 0x00007ffff64b4c8c in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#11 0x00007ffff64b9e56 in QApplication::notify(QObject*, QEvent*) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#12 0x00007ffff6e0ac2d in QCoreApplication::notifyInternal(QObject*, QEvent*) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#13 0x00007ffff64eabea in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#14 0x00007ffff64eb5bc in QWidgetPrivate::paintSiblingsRecursive(QPaintDevice*, QList<QObject*> const&, int, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#15 0x00007ffff64ea786 in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#16 0x00007ffff64c1233 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#17 0x00007ffff64e0e2f in QWidgetPrivate::syncBackingStore() ()
   from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#18 0x00007ffff64f0112 in QWidget::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#19 0x00007ffff64b4c8c in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#20 0x00007ffff64b9e56 in QApplication::notify(QObject*, QEvent*) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#21 0x00007ffff6e0ac2d in QCoreApplication::notifyInternal(QObject*, QEvent*) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#22 0x00007ffff6e0ce07 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#23 0x00007ffff6e57cd3 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#24 0x00007ffff130de04 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#25 0x00007ffff130e048 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#26 0x00007ffff130e0ec in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#27 0x00007ffff6e5798c in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#28 0x00007ffff6e0996b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#29 0x00007ffff6e100e1 in QCoreApplication::exec() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#30 0x0000000000578ca3 in main (argc=1, argv=<optimized out>)
    at /work/pangerca/colmap/src/exe/colmap.cc:49
```

**Comment by ahojnnes** [comment]
@andrejpan Can you please check the latest commit in master and report if the error still occurs? Thanks!

**Comment by andrejpan** [comment]
At fusion step I get this error:
```
(gdb) r
Starting program: /work/pangerca/colmap/build/src/exe/colmap 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffea2fb700 (LWP 15469)]
[New Thread 0x7fffe9afa700 (LWP 15470)]
[New Thread 0x7fffe72f9700 (LWP 15471)]
[New Thread 0x7fffe4af8700 (LWP 15472)]
[New Thread 0x7fffe22f7700 (LWP 15473)]
[New Thread 0x7fffdfaf6700 (LWP 15474)]
[New Thread 0x7fffdd2f5700 (LWP 15475)]
[New Thread 0x7fffd4de1700 (LWP 15476)]
[New Thread 0x7fffc6162700 (LWP 15479)]
[New Thread 0x7fffc5961700 (LWP 15480)]
[New Thread 0x7fffc5160700 (LWP 15481)]
[New Thread 0x7fffc495f700 (LWP 15482)]
[Thread 0x7fffc5160700 (LWP 15481) exited]
[New Thread 0x7fffc5160700 (LWP 15483)]
[New Thread 0x7fffaadbd700 (LWP 15484)]
[New Thread 0x7fffaa55c700 (LWP 15485)]
[New Thread 0x7fffa9d5b700 (LWP 15486)]
[Thread 0x7fffc495f700 (LWP 15482) exited]
[Thread 0x7fffa9d5b700 (LWP 15486) exited]
[Thread 0x7fffc5160700 (LWP 15483) exited]
[Thread 0x7fffaadbd700 (LWP 15484) exited]
[New Thread 0x7fffaadbd700 (LWP 15487)]
[New Thread 0x7fffc5160700 (LWP 15488)]
[New Thread 0x7fffa9d5b700 (LWP 15489)]
[New Thread 0x7fffc495f700 (LWP 15490)]
[New Thread 0x7fffa955a700 (LWP 15491)]
[New Thread 0x7fffa8d59700 (LWP 15492)]
[Thread 0x7fffc495f700 (LWP 15490) exited]
[Thread 0x7fffaa55c700 (LWP 15485) exited]
[Thread 0x7fffa9d5b700 (LWP 15489) exited]
[Thread 0x7fffa8d59700 (LWP 15492) exited]
[Thread 0x7fffa955a700 (LWP 15491) exited]
[Thread 0x7fffaadbd700 (LWP 15487) exited]
[New Thread 0x7fffa955a700 (LWP 15493)]
[New Thread 0x7fffaadbd700 (LWP 15494)]
[Thread 0x7fffc5160700 (LWP 15488) exited]
[Thread 0x7fffa955a700 (LWP 15493) exited]
[New Thread 0x7fffa955a700 (LWP 15495)]
[Thread 0x7fffaadbd700 (LWP 15494) exited]
[New Thread 0x7fffaadbd700 (LWP 15496)]
[Thread 0x7fffa955a700 (LWP 15495) exited]
[Thread 0x7fffaadbd700 (LWP 15496) exited]
[Thread 0x7fffc5961700 (LWP 15480) exited]
[Thread 0x7fffc6162700 (LWP 15479) exited]
[Thread 0x7fffd4de1700 (LWP 15476) exited]
[Thread 0x7fffdd2f5700 (LWP 15475) exited]
[Thread 0x7fffdfaf6700 (LWP 15474) exited]
[Thread 0x7fffe22f7700 (LWP 15473) exited]
[Thread 0x7fffe72f9700 (LWP 15471) exited]
[Thread 0x7fffe9afa700 (LWP 15470) exited]
[Thread 0x7fffea2fb700 (LWP 15469) exited]
[Thread 0x7ffff7f96800 (LWP 15468) exited]

Program terminated with signal SIGKILL, Killed.
The program no longer exists.
(gdb) bt
No stack.
```
 Is there some other way how to get the stack output?

**Comment by ahojnnes** [comment]
This was caused by the fusion code using too much RAM. With the latest commits, the fusion has an option to define the cache size, which should allow to fuse large models on systems with few RAM. Thanks for reporting this issue!

**Comment by alexsmartens** [comment]
Hi @ahojnnes 
I might be having a similar issue. 
I start Fusion and have a windows message "colmap.exe has stopped working". 

Here is my colmap log (no log in terminal):

```
StereoFusion: :Options
------------------------------------
min_num_pixels: 5
mux_num_pixels: 1000
max_traversal_depth: 100
max_reproj_error: 2
max_depth_error: 0.01
max_normal_error: 10

Reading workspace...
Reading configuration...
Fusion image [1/400] in 327.416s
Fusion image [2/400] in 125.624s
Fusion image [3/400] in 1334.926s
Fusion image [4/400] 
```

What would you recommend?

**Comment by ahojnnes** [comment]
This happens when you run out of RAM and your system then kills the COLMAP process. Please refer to the documentation for more info: https://colmap.github.io/faq.html#reduce-memory-usage-during-dense-reconstruction
