### ISSUE TITLE
How to get an nvm with both cameras and points?

### ISSUE THREAD

**Issue by Enderych** [colmap/colmap#808]
Hello, 
after automatic reconstruction, now I have a sparse document which includes cameras.bin, images.bin and points3D.bin. I can use model_converter to transfer them to '.txt', and then read the information. But I can not convert them into 'NVM' format. The error shows 'Check failed: file.is_open() path_to_output'.
Then I tried to use colmap GUI, firstly input model from fused.ply, then output model with 'NVM' model, but then I found that there are only points information inside the nvm document, no cameras and images poses information. How can I get an nvm with both cameras and points?

**Comment by tsattler** [comment]
Given the error message that you provide, it seems that you are either trying to write the .nvm file to a path that does not exist or you do not specify the name of the output file.
fused.ply contains a dense point cloud. Why would you expect it to contain camera information?

**Comment by Enderych** [comment]
Thank you, you are right, I should specify the name of .nvm document, not only the path.

Do you know how to build an empty database.db, just like you offered in the aachen-day-and-night dataset, which is only 700 kB with image and camera intrinsics lists?

**Comment by Enderych** [comment]
@tsattler 
Hello, I ask the last question because when I doing 'reconstruction_pipeline.py' in your visual localization benchmark, I met such an error:
Traceback (most recent call last):
  File "reconstruction_pipeline.py", line 335, in <module>
    import_features(images, paths, args)
  File "reconstruction_pipeline.py", line 165, in import_features
    (image_id, keypoints.shape[0], keypoints.shape[1], keypoints_str))
sqlite3.IntegrityError: UNIQUE constraint failed: keypoints.image_id

The last time I met a similar question was that I used duplicate image pairs. This time I guess it was because I build a database.db with 'colmap feature_extractor' command, which includes all images ID and feature points inside (1.3GB), so I am curious how you made the 700kB database.db for Aachen dataset. I have checked there are also camera ID and intrinsics inside it, but why there was no error of 'UNIQUE constraint'?

Thanks in advance.

**Comment by tsattler** [comment]
We created the lightweight database by directly modifying the database using SQLite.

The repository where you got the reconstruction_pipeline.py file also contains code to use a non-empty database for importing features.

**Comment by Enderych** [comment]
Thank you, I am not familiar with SQLite, I don't know how to build a database from scratch with it. But with your hint, I use sqlite3 to extract information from a non-empty database to ASCII, then delete the features, descriptors, and matches manually. Then I convert it back to the database, now it works with reconstruction_pipeline.py. Thanks again!
