### ISSUE TITLE
eigen zipfile download link does not work anymore

### ISSUE THREAD

**Issue by tompollok** [colmap/colmap#973]
**Describe the bug**

https://bitbucket.org/eigen/eigen/get/3.3.7.zip
Repository eigen/eigen not found

They moved to gitlab:
https://gitlab.com/libeigen/eigen

https://gitlab.com/libeigen/eigen/-/archive/3.3.7/eigen-3.3.7.zip

When i tried to update that link and the hash I got an http error: 403 

**To Reproduce**
Building on windows 10 using python build script.

**Comment by ahojnnes** [comment]
Thanks, fixed. Note that I do recommend to use the new vcpkg based build on Windows, see http://colmap.github.io/install.html#id3

**Comment by NIRVANALAN** [comment]
Seems that it still doesn't work, with the new URL
```
Traceback (most recent call last):
  File "build.py", line 554, in <module>
    main()
  File "build.py", line 531, in main
    build_eigen(args)
  File "build.py", line 226, in build_eigen
    download_zipfile(url, archive_path, args.build_path,
  File "build.py", line 188, in download_zipfile
    urllib.request.urlretrieve(url, archive_path)
  File "/mnt/lustre/yslan/local/anaconda3/lib/python3.8/urllib/request.py", line 247, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
  File "/mnt/lustre/yslan/local/anaconda3/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/mnt/lustre/yslan/local/anaconda3/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/mnt/lustre/yslan/local/anaconda3/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/mnt/lustre/yslan/local/anaconda3/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/mnt/lustre/yslan/local/anaconda3/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/mnt/lustre/yslan/local/anaconda3/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
```

**Comment by jasonyzhang** [comment]
It is likely that gitlab is looking for a user agent when downloading. A temporary workaround would be to `wget http://gitlab.com/libeigen/eigen/-/archive/3.3.7/eigen-3.3.7.zip` in build/__download__
